import json
import os
import re
import unicodedata
from datetime import datetime, timezone


DATE = "2026-06-30"

TOP_JSON = f"public/predictions_{DATE}.json"
ALL_JSON = f"public/all_predictions_{DATE}.json"

OUT_DIR = "public/backtest_2026-06-30"
OUT_JSON = f"{OUT_DIR}/index.json"
OUT_HTML = f"{OUT_DIR}/index.html"


DISCLAIMER = "The data generated by the Backstage Talks STAT model is for statistical and informational purposes only."


# Wimbledon Day 2 / 30 JUN 2026 result seed.
# Zdroj: Wimbledon official results page + ESPN/LiveScore cross-check.
RESULTS = [
    # Gentlemen's Singles
    {"winner": "Taylor Fritz", "loser": "Dusan Lajovic", "score": "6-3 6-4 6-3"},
    {"winner": "Alex de Minaur", "loser": "Roman Burruchaga", "score": "5-7 7-5 7-6 6-0"},
    {"winner": "Brandon Nakashima", "loser": "Jack Pinnington Jones", "score": "6-3 7-6 7-5"},
    {"winner": "Quentin Halys", "loser": "Matteo Arnaldi", "score": "3-6 6-1 7-6 7-5 6-3"},
    {"winner": "Kamil Majchrzak", "loser": "Alejandro Tabilo", "score": "6-3 7-5 7-5"},
    {"winner": "Kyrian Jacquet", "loser": "Vilius Gaubas", "score": "6-3 6-4 7-6"},
    {"winner": "Adrian Mannarino", "loser": "Titouan Droguet", "score": "6-2 6-4 6-1"},
    {"winner": "Gabriel Diallo", "loser": "Benjamin Bonzi", "score": "1-6 4-6 7-6 7-5 6-3 RET"},
    {"winner": "Yannick Hanfmann", "loser": "Giovanni Mpetshi Perricard", "score": "6-7 6-7 7-6 6-2 6-3"},
    {"winner": "Jaime Faria", "loser": "Sho Shimabukuro", "score": "7-6 6-3 6-7 2-6 6-3"},
    {"winner": "Jesper de Jong", "loser": "Rinky Hijikata", "score": "7-6 7-6 3-6 5-7 6-4"},
    {"winner": "Zachary Svajda", "loser": "Pablo Llamas Ruiz", "score": "6-1 6-2 6-4"},
    {"winner": "Valentin Royer", "loser": "Harry Wendelken", "score": "4-6 6-3 6-3 6-3"},
    {"winner": "Jaume Munar", "loser": "Francisco Cerundolo", "score": "6-1 6-4 6-3"},
    {"winner": "Jacob Fearnley", "loser": "Alex Michelsen", "score": "3-6 4-6 6-2 6-3 6-2"},
    {"winner": "Arthur Fery", "loser": "Damir Dzumhur", "score": "3-6 6-2 6-2 6-1"},

    # Ladies' Singles
    {"winner": "Iga Swiatek", "loser": "Taylor Townsend", "score": "6-1 2-6 6-3"},
    {"winner": "Amanda Anisimova", "loser": "Lina Gjorcheska", "score": "6-3 6-2"},
    {"winner": "Tyra Caterina Grant", "loser": "Katie Boulter", "score": "6-4 6-2"},
    {"winner": "Jasmine Paolini", "loser": "Robin Montgomery", "score": "0-6 6-4 7-5"},
    {"winner": "Madison Keys", "loser": "Kayla Day", "score": "6-7 7-5 6-4"},
    {"winner": "Karolina Pliskova", "loser": "Tereza Valentova", "score": "6-3 6-4"},
    {"winner": "Viktorija Golubic", "loser": "Iryna Shymanovich", "score": "6-2 2-6 6-1"},
    {"winner": "Kamilla Rakhimova", "loser": "Anhelina Kalinina", "score": "4-6 6-4 7-5"},
    {"winner": "Kimberly Birrell", "loser": "Alina Korneeva", "score": "6-3 0-6 6-2"},
    {"winner": "Maria Timofeeva", "loser": "Beatriz Haddad Maia", "score": "6-3 6-2"},
    {"winner": "Sofia Kenin", "loser": "Petra Marcinko", "score": "7-6 7-6"},
    {"winner": "Maria Sakkari", "loser": "Clara Tauson", "score": "6-3 6-3"},
    {"winner": "Katie Swan", "loser": "Irina-Camelia Begu", "score": "6-4 6-4"},
    {"winner": "Marie Bouzkova", "loser": "Talia Gibson", "score": "6-1 3-6 6-2"},
    {"winner": "Elena Rybakina", "loser": "Lois Boisson", "score": "6-4 1-6 6-3"},
    {"winner": "Daria Snigur", "loser": "Elina Svitolina", "score": "7-5 6-2"},
    {"winner": "Linda Noskova", "loser": "Ella Seidel", "score": "6-4 6-3"},
    {"winner": "Marta Kostyuk", "loser": "Nadia Podoroska", "score": "6-1 6-2"},
    {"winner": "Diana Shnaider", "loser": "Eva Lys", "score": "7-5 6-1"},
    {"winner": "Sorana Cirstea", "loser": "Sara Bejlek", "score": "6-1 7-6"},
    {"winner": "Ashlyn Krueger", "loser": "Donna Vekic", "score": "3-6 7-6 6-4"},
    {"winner": "Camila Osorio", "loser": "Simona Waltert", "score": "6-2 6-1"},
    {"winner": "Liudmila Samsonova", "loser": "Polina Kudermetova", "score": "6-3 6-3"},
]


def normalize_name(name):
    if not name:
        return ""

    text = str(name)
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.lower().strip()
    text = text.replace("-", " ")
    text = re.sub(r"[^a-z0-9\s']", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def tokens(name):
    return set(normalize_name(name).split())


def last_token(name):
    parts = normalize_name(name).split()
    if not parts:
        return ""
    return parts[-1]


def similarity(a, b):
    a_tokens = tokens(a)
    b_tokens = tokens(b)

    if not a_tokens or not b_tokens:
        return 0.0

    overlap = len(a_tokens.intersection(b_tokens))
    total = max(len(a_tokens), len(b_tokens))

    score = overlap / total

    if last_token(a) and last_token(a) == last_token(b):
        score += 0.35

    return min(score, 1.0)


def same_player(a, b):
    return similarity(a, b) >= 0.55


def load_json(path):
    if not os.path.exists(path):
        return []

    with open(path, encoding="utf-8") as f:
        return json.load(f)


def find_result_for_match(player1, player2):
    best = None
    best_score = 0.0

    for result in RESULTS:
        winner = result["winner"]
        loser = result["loser"]

        direct_score = min(
            similarity(player1, winner),
            similarity(player2, loser),
        )

        reverse_score = min(
            similarity(player1, loser),
            similarity(player2, winner),
        )

        score = max(direct_score, reverse_score)

        if score > best_score:
            best_score = score
            best = result

    if best and best_score >= 0.55:
        return best

    return None


def opponent_of(prediction):
    if prediction.get("opponent"):
        return prediction.get("opponent")

    pick = prediction.get("pick")
    player1 = prediction.get("player1")
    player2 = prediction.get("player2")

    if pick == player1:
        return player2

    return player1


def evaluate_prediction(prediction):
    player1 = prediction.get("player1")
    player2 = prediction.get("player2")
    pick = prediction.get("pick")

    result = find_result_for_match(player1, player2)

    if not result:
        return {
            "status": "UNKNOWN",
            "winner": None,
            "score": None,
            "profit": 0,
        }

    winner = result["winner"]
    score = result["score"]

    odds = prediction.get("odds")

    if same_player(pick, winner):
        profit = float(odds) - 1 if odds else 0
        status = "WON"
    else:
        profit = -1 if odds else 0
        status = "LOST"

    return {
        "status": status,
        "winner": winner,
        "score": score,
        "profit": round(profit, 3),
    }


def evaluate_feed(name, predictions):
    rows = []

    for prediction in predictions:
        evaluation = evaluate_prediction(prediction)

        row = {
            "feed": name,
            "pick": prediction.get("pick"),
            "opponent": opponent_of(prediction),
            "match": prediction.get("match"),
            "probability": prediction.get("probability"),
            "odds": prediction.get("odds"),
            "status": evaluation["status"],
            "winner": evaluation["winner"],
            "score": evaluation["score"],
            "profit": evaluation["profit"],
        }

        rows.append(row)

    return rows


def summarize(rows):
    settled = [r for r in rows if r["status"] in ["WON", "LOST"]]
    won = [r for r in settled if r["status"] == "WON"]
    lost = [r for r in settled if r["status"] == "LOST"]
    unknown = [r for r in rows if r["status"] == "UNKNOWN"]

    total_profit = round(sum(r["profit"] for r in settled), 3)
    total_bets = len(settled)
    hit_rate = round(len(won) / total_bets, 3) if total_bets else 0
    roi = round(total_profit / total_bets, 3) if total_bets else 0

    avg_odds_values = [
        float(r["odds"]) for r in settled
        if r.get("odds") is not None
    ]

    avg_odds = round(sum(avg_odds_values) / len(avg_odds_values), 3) if avg_odds_values else 0

    return {
        "total": len(rows),
        "settled": total_bets,
        "won": len(won),
        "lost": len(lost),
        "unknown": len(unknown),
        "hit_rate": hit_rate,
        "avg_odds": avg_odds,
        "profit_1u": total_profit,
        "roi": roi,
    }


def percent(value):
    try:
        return f"{float(value) * 100:.1f}%"
    except Exception:
        return "-"


def fmt(value):
    if value is None:
        return "-"
    return str(value)


def render_html(top_rows, all_rows, top_summary, all_summary):
    def summary_block(title, summary):
        return f"""
<div class="summary-card">
<h2>{title}</h2>
<p>Total: {summary["total"]}</p>
<p>Settled: {summary["settled"]}</p>
<p>Won: {summary["won"]}</p>
<p>Lost: {summary["lost"]}</p>
<p>Unknown: {summary["unknown"]}</p>
<p>Hit rate: {summary["hit_rate"] * 100:.1f}%</p>
<p>Avg odds: {summary["avg_odds"]}</p>
<p>Profit 1u: {summary["profit_1u"]}u</p>
<p>ROI: {summary["roi"] * 100:.1f}%</p>
</div>
"""

    def table(title, rows):
        body = ""

        if not rows:
            body = """
<tr>
<td colspan="8">No rows available.</td>
</tr>
"""
        else:
            for i, row in enumerate(rows, 1):
                body += f"""
<tr>
<td>#{i}</td>
<td>{row.get("pick")}</td>
<td>{row.get("opponent")}</td>
<td>{percent(row.get("probability"))}</td>
<td>{fmt(row.get("odds"))}</td>
<td>{row.get("status")}</td>
<td>{fmt(row.get("winner"))}</td>
<td>{fmt(row.get("score"))}</td>
<td>{row.get("profit")}u</td>
</tr>
"""

        return f"""
<h2>{title}</h2>
<table>
<thead>
<tr>
<th>#</th>
<th>Pick</th>
<th>Opponent</th>
<th>Win %</th>
<th>Odds</th>
<th>Status</th>
<th>Winner</th>
<th>Score</th>
<th>Profit</th>
</tr>
</thead>
<tbody>
{body}
</tbody>
</table>
"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Backtest Wimbledon 2026-06-30</title>
<style>
body {{
    background: #160b0b;
    color: #ffffff;
    font-family: Arial, Helvetica, sans-serif;
    padding: 24px;
}}
h1 {{
    font-size: 38px;
    margin-bottom: 8px;
}}
.disclaimer {{
    color: #c7c7c7;
    font-size: 12px;
    margin-bottom: 24px;
}}
.summary {{
    display: flex;
    gap: 16px;
    flex-wrap: wrap;
    margin-bottom: 28px;
}}
.summary-card {{
    background: #201313;
    padding: 14px 18px;
    border-radius: 10px;
    min-width: 240px;
}}
table {{
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 30px;
}}
th, td {{
    border-bottom: 1px solid #3a2525;
    padding: 10px;
    text-align: left;
    vertical-align: top;
}}
th {{
    color: #f3f3f3;
}}
tr:hover {{
    background: #2a1616;
}}
</style>
</head>
<body>

<h1>Backtest Wimbledon 2026-06-30</h1>
<div class="disclaimer">
The data generated by the Backstage Talks STAT model is for statistical and informational purposes only.
</div>

<div class="summary">
{summary_block("TOP summary", top_summary)}
{summary_block("ALL summary", all_summary)}
</div>

{table("TOP predictions vs results", top_rows)}
{table("ALL predictions vs results", all_rows)}

</body>
</html>
"""


def run():
    os.makedirs(OUT_DIR, exist_ok=True)

    top_predictions = load_json(TOP_JSON)
    all_predictions = load_json(ALL_JSON)

    top_rows = evaluate_feed("TOP", top_predictions)
    all_rows = evaluate_feed("ALL", all_predictions)

    top_summary = summarize(top_rows)
    all_summary = summarize(all_rows)

    output = {
        "date": DATE,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "sources": [
            "Wimbledon official results page",
            "ESPN scoreboard cross-check",
            "LiveScore completed matches cross-check",
        ],
        "top_summary": top_summary,
        "all_summary": all_summary,
        "top_rows": top_rows,
        "all_rows": all_rows,
    }

    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    with open(OUT_HTML, "w", encoding="utf-8") as f:
        f.write(render_html(
            top_rows=top_rows,
            all_rows=all_rows,
            top_summary=top_summary,
            all_summary=all_summary,
        ))

    print("WROTE", OUT_JSON)
    print("WROTE", OUT_HTML)
    print("TOP SUMMARY:", top_summary)
    print("ALL SUMMARY:", all_summary)


if __name__ == "__main__":
    run()
