import json
import os
import re
import unicodedata
from datetime import datetime, timezone

from sackmann_loader import load_all_matches
from elo_engine import build_elo, predict


DATE = "2026-06-22_to_2026-06-28"
CUTOFF_DATE = "20260622"

OUT_DIR = "public/backtest_eastbourne_2026"
OUT_JSON = f"{OUT_DIR}/index.json"
OUT_HTML = f"{OUT_DIR}/index.html"

DISCLAIMER = (
    "The data generated by the Backstage Talks STAT model is for statistical "
    "and informational purposes only."
)


# ATP Eastbourne 2026 main draw results.
# Sources:
# - Flashscore ATP Eastbourne 2026 results archive
# - Livesport ATP Eastbourne 2026 bracket/results archive
#
# This is an ELO-only retro backtest.
# No historical odds are used here.
RESULTS = [
    # 1/16-finals
    {
        "round": "1/16-finals",
        "player1": "Jan Choinski",
        "player2": "Alexei Popyrin",
        "winner": "Jan Choinski",
        "score": "1-6 6-2 6-2",
    },
    {
        "round": "1/16-finals",
        "player1": "Daniel Altmaier",
        "player2": "Aleksandar Kovacevic",
        "winner": "Daniel Altmaier",
        "score": "6-4 7-6",
    },
    {
        "round": "1/16-finals",
        "player1": "Zizou Bergs",
        "player2": "Jaume Munar",
        "winner": "Zizou Bergs",
        "score": "6-2 6-4",
    },
    {
        "round": "1/16-finals",
        "player1": "Thiago Agustin Tirante",
        "player2": "Hamish Stewart",
        "winner": "Thiago Agustin Tirante",
        "score": "7-5 6-2",
    },
    {
        "round": "1/16-finals",
        "player1": "Roman Andres Burruchaga",
        "player2": "Arthur Fery",
        "winner": "Arthur Fery",
        "score": "2-6 6-4 7-5",
    },
    {
        "round": "1/16-finals",
        "player1": "Raphael Collignon",
        "player2": "Juan Manuel Cerundolo",
        "winner": "Juan Manuel Cerundolo",
        "score": "4-6 6-4 6-7",
    },
    {
        "round": "1/16-finals",
        "player1": "Marcos Giron",
        "player2": "Jack Draper",
        "winner": "Jack Draper",
        "score": "4-6 6-7",
    },
    {
        "round": "1/16-finals",
        "player1": "Jack Pinnington Jones",
        "player2": "Marco Trungelliti",
        "winner": "Jack Pinnington Jones",
        "score": "5-7 6-3 7-5",
    },
    {
        "round": "1/16-finals",
        "player1": "Gabriel Diallo",
        "player2": "Terence Atmane",
        "winner": "Gabriel Diallo",
        "score": "6-7 6-4 7-5",
    },
    {
        "round": "1/16-finals",
        "player1": "Ugo Humbert",
        "player2": "Mattia Bellucci",
        "winner": "Ugo Humbert",
        "score": "7-6 6-7 6-4",
    },
    {
        "round": "1/16-finals",
        "player1": "Jenson Brooksby",
        "player2": "Aleksandar Vukic",
        "winner": "Jenson Brooksby",
        "score": "7-5 6-1",
    },
    {
        "round": "1/16-finals",
        "player1": "Matteo Arnaldi",
        "player2": "Giles Hussey",
        "winner": "Giles Hussey",
        "score": "4-6 2-6",
    },

    # 1/8-finals
    {
        "round": "1/8-finals",
        "player1": "Giles Hussey",
        "player2": "Jan Choinski",
        "winner": "Jan Choinski",
        "score": "4-6 7-6 4-6",
    },
    {
        "round": "1/8-finals",
        "player1": "Daniel Altmaier",
        "player2": "Zizou Bergs",
        "winner": "Zizou Bergs",
        "score": "3-6 2-3 RET",
    },
    {
        "round": "1/8-finals",
        "player1": "Jack Draper",
        "player2": "Jack Pinnington Jones",
        "winner": "Jack Draper",
        "score": "7-5 6-4",
    },
    {
        "round": "1/8-finals",
        "player1": "Gabriel Diallo",
        "player2": "Tomas Martin Etcheverry",
        "winner": "Gabriel Diallo",
        "score": "6-7 7-6 6-3",
    },
    {
        "round": "1/8-finals",
        "player1": "Ugo Humbert",
        "player2": "Jenson Brooksby",
        "winner": "Ugo Humbert",
        "score": "6-3 6-2",
    },
    {
        "round": "1/8-finals",
        "player1": "Arthur Fery",
        "player2": "Juan Manuel Cerundolo",
        "winner": "Juan Manuel Cerundolo",
        "score": "2-6 6-7",
    },
    {
        "round": "1/8-finals",
        "player1": "Giles Hussey",
        "player2": "Quentin Halys",
        "winner": "Quentin Halys",
        "score": "1-6 5-7",
    },
    {
        "round": "1/8-finals",
        "player1": "Samuel T.",
        "player2": "Thiago Agustin Tirante",
        "winner": "Samuel T.",
        "score": "6-1 7-6",
    },

    # Quarter-finals
    {
        "round": "Quarter-finals",
        "player1": "Jan Choinski",
        "player2": "Zizou Bergs",
        "winner": "Zizou Bergs",
        "score": "3-6 3-6",
    },
    {
        "round": "Quarter-finals",
        "player1": "Samuel T.",
        "player2": "Juan Manuel Cerundolo",
        "winner": "Samuel T.",
        "score": "6-3 6-1",
    },
    {
        "round": "Quarter-finals",
        "player1": "Jack Draper",
        "player2": "Gabriel Diallo",
        "winner": "Jack Draper",
        "score": "6-1 6-4",
    },
    {
        "round": "Quarter-finals",
        "player1": "Ugo Humbert",
        "player2": "Quentin Halys",
        "winner": "Ugo Humbert",
        "score": "6-3 6-4",
    },

    # Semi-finals
    {
        "round": "Semi-finals",
        "player1": "Zizou Bergs",
        "player2": "Samuel T.",
        "winner": "Zizou Bergs",
        "score": "4-6 7-6 6-2",
    },
    {
        "round": "Semi-finals",
        "player1": "Jack Draper",
        "player2": "Ugo Humbert",
        "winner": "Ugo Humbert",
        "score": "5-7 6-7",
    },

    # Final
    {
        "round": "Final",
        "player1": "Zizou Bergs",
        "player2": "Ugo Humbert",
        "winner": "Zizou Bergs",
        "score": "3-6 7-6 6-4",
    },
]


def normalize_name(name):
    if not name:
        return ""

    text = str(name)
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.lower().strip()
    text = text.replace("-", " ")
    text = re.sub(r"[^a-z0-9\s']", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def same_player(a, b):
    return normalize_name(a) == normalize_name(b)


def filter_history_before_cutoff(matches):
    filtered = []

    for match in matches:
        date = str(match.get("date") or "0")

        if date != "0" and date < CUTOFF_DATE:
            filtered.append(match)

    return filtered


def build_backtest_elo_store():
    print("LOADING HISTORICAL MATCHES FOR EASTBOURNE BACKTEST...")

    all_history = load_all_matches(2018, 2030)

    print("HISTORICAL MATCHES LOADED:", len(all_history))

    cutoff_history = filter_history_before_cutoff(all_history)

    print("HISTORICAL MATCHES BEFORE", CUTOFF_DATE, ":", len(cutoff_history))

    if not cutoff_history:
        raise Exception("NO CUTOFF HISTORY FOR EASTBOURNE BACKTEST")

    store = build_elo(cutoff_history)

    print("EASTBOURNE BACKTEST ELO STORE PLAYERS:", len(store))

    if len(store) < 200:
        raise Exception("TOO FEW EASTBOURNE BACKTEST ELO PLAYERS")

    return store


def make_prediction_for_match(match, elo_store):
    player1 = match["player1"]
    player2 = match["player2"]

    elo_prediction = predict(
        player1,
        player2,
        "Grass",
        elo_store,
    )

    prob1 = elo_prediction["probability_player1"]
    prob2 = elo_prediction["probability_player2"]

    if prob1 >= prob2:
        pick = player1
        opponent = player2
        probability = prob1
    else:
        pick = player2
        opponent = player1
        probability = prob2

    status = "WON" if same_player(pick, match["winner"]) else "LOST"

    return {
        "round": match["round"],
        "player1": player1,
        "player2": player2,
        "match": f"{player1} vs {player2}",
        "pick": pick,
        "opponent": opponent,
        "winner": match["winner"],
        "score": match["score"],
        "probability": round(probability, 3),
        "status": status,
        "elo_found_player1": elo_prediction.get("elo_found_player1"),
        "elo_found_player2": elo_prediction.get("elo_found_player2"),
        "elo_player1": round(elo_prediction.get("elo_player1", 1500), 1),
        "elo_player2": round(elo_prediction.get("elo_player2", 1500), 1),
        "elo_matches_player1": elo_prediction.get("elo_matches_player1"),
        "elo_matches_player2": elo_prediction.get("elo_matches_player2"),
        "elo_reliability_player1": elo_prediction.get("elo_reliability_player1"),
        "elo_reliability_player2": elo_prediction.get("elo_reliability_player2"),
        "model": elo_prediction.get("model"),
    }


def summarize(rows):
    total = len(rows)
    won = len([r for r in rows if r["status"] == "WON"])
    lost = len([r for r in rows if r["status"] == "LOST"])

    hit_rate = round(won / total, 3) if total else 0

    found_rows = [
        r for r in rows
        if r.get("elo_found_player1") and r.get("elo_found_player2")
    ]

    found_total = len(found_rows)
    found_won = len([r for r in found_rows if r["status"] == "WON"])
    found_lost = len([r for r in found_rows if r["status"] == "LOST"])
    found_hit_rate = round(found_won / found_total, 3) if found_total else 0

    max_probability = max([r["probability"] for r in rows], default=0)

    avg_probability = round(
        sum([r["probability"] for r in rows]) / total,
        3
    ) if total else 0

    return {
        "total": total,
        "won": won,
        "lost": lost,
        "hit_rate": hit_rate,
        "elo_found_both": found_total,
        "elo_found_both_won": found_won,
        "elo_found_both_lost": found_lost,
        "elo_found_both_hit_rate": found_hit_rate,
        "max_probability": max_probability,
        "avg_probability": avg_probability,
    }


def percent(value):
    try:
        return f"{float(value) * 100:.1f}%"
    except Exception:
        return "-"


def render_html(rows, summary):
    body = ""

    if not rows:
        body = """
<tr>
<td colspan="11">No rows available.</td>
</tr>
"""
    else:
        for i, row in enumerate(rows, 1):
            body += f"""
<tr>
<td>#{i}</td>
<td>{row["round"]}</td>
<td>{row["pick"]}</td>
<td>{row["opponent"]}</td>
<td>{percent(row["probability"])}</td>
<td>{row["status"]}</td>
<td>{row["winner"]}</td>
<td>{row["score"]}</td>
<td>{row["elo_found_player1"]} / {row["elo_found_player2"]}</td>
<td>{row["elo_player1"]} / {row["elo_player2"]}</td>
<td>{row["elo_matches_player1"]} / {row["elo_matches_player2"]}</td>
</tr>
"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Retro Backtest ATP Eastbourne 2026</title>
<style>
body {{
    background: #160b0b;
    color: #ffffff;
    font-family: Arial, Helvetica, sans-serif;
    padding: 24px;
}}
h1 {{
    font-size: 38px;
    margin-bottom: 8px;
}}
.disclaimer {{
    color: #c7c7c7;
    font-size: 12px;
    margin-bottom: 24px;
}}
.summary {{
    background: #201313;
    padding: 14px 18px;
    border-radius: 10px;
    max-width: 560px;
    margin-bottom: 28px;
}}
table {{
    width: 100%;
    border-collapse: collapse;
}}
th, td {{
    border-bottom: 1px solid #3a2525;
    padding: 10px;
    text-align: left;
    vertical-align: top;
}}
th {{
    color: #f3f3f3;
}}
tr:hover {{
    background: #2a1616;
}}
</style>
</head>
<body>

<h1>Retro Backtest ATP Eastbourne 2026</h1>
<div class="disclaimer">{DISCLAIMER}</div>

<div class="summary">
<h2>Summary</h2>
<p>Total: {summary["total"]}</p>
<p>Won: {summary["won"]}</p>
<p>Lost: {summary["lost"]}</p>
<p>Hit rate: {summary["hit_rate"] * 100:.1f}%</p>
<p>ELO found both: {summary["elo_found_both"]}</p>
<p>ELO-found WON: {summary["elo_found_both_won"]}</p>
<p>ELO-found LOST: {summary["elo_found_both_lost"]}</p>
<p>ELO-found-only hit rate: {summary["elo_found_both_hit_rate"] * 100:.1f}%</p>
<p>Avg probability: {percent(summary["avg_probability"])}</p>
<p>Max probability: {percent(summary["max_probability"])}</p>
</div>

<table>
<thead>
<tr>
<th>#</th>
<th>Round</th>
<th>Pick</th>
<th>Opponent</th>
<th>Win %</th>
<th>Status</th>
<th>Winner</th>
<th>Score</th>
<th>ELO found</th>
<th>ELO</th>
<th>ELO matches</th>
</tr>
</thead>
<tbody>
{body}
</tbody>
</table>

</body>
</html>
"""


def run():
    os.makedirs(OUT_DIR, exist_ok=True)

    elo_store = build_backtest_elo_store()

    rows = [
        make_prediction_for_match(match, elo_store)
        for match in RESULTS
    ]

    rows.sort(key=lambda x: x["probability"], reverse=True)

    summary = summarize(rows)

    output = {
        "date": DATE,
        "mode": "retro_backtest_with_cutoff",
        "cutoff_date": CUTOFF_DATE,
        "tournament": "ATP Eastbourne 2026",
        "surface": "Grass",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": summary,
        "rows": rows,
    }

    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    with open(OUT_HTML, "w", encoding="utf-8") as f:
        f.write(render_html(rows, summary))

    print("WROTE", OUT_JSON)
    print("WROTE", OUT_HTML)
    print("SUMMARY:", summary)


if __name__ == "__main__":
    run()
