import json
import os
import re
import unicodedata
from datetime import datetime, timezone

from sackmann_loader import load_all_matches
from elo_engine import build_elo, predict


DATE = "2026-06-30"
CUTOFF_DATE = "20260630"

OUT_DIR = "public/backtest_2026-06-30"
OUT_JSON = f"{OUT_DIR}/index.json"
OUT_HTML = f"{OUT_DIR}/index.html"

DISCLAIMER = (
    "The data generated by the Backstage Talks STAT model is for statistical "
    "and informational purposes only."
)


# Wimbledon Day 2 / 30 JUN 2026 result seed.
# Source: Wimbledon official results page.
RESULTS = [
    # Gentlemen's Singles
    {"player1": "Taylor Fritz", "player2": "Dusan Lajovic", "winner": "Taylor Fritz", "score": "6-3 6-4 6-3"},
    {"player1": "Alex de Minaur", "player2": "Roman Burruchaga", "winner": "Alex de Minaur", "score": "5-7 7-5 7-6 6-0"},
    {"player1": "Brandon Nakashima", "player2": "Jack Pinnington Jones", "winner": "Brandon Nakashima", "score": "6-3 7-6 7-5"},
    {"player1": "Matteo Arnaldi", "player2": "Quentin Halys", "winner": "Quentin Halys", "score": "3-6 6-1 7-6 7-5 6-3"},
    {"player1": "Kamil Majchrzak", "player2": "Alejandro Tabilo", "winner": "Kamil Majchrzak", "score": "6-3 7-5 7-5"},
    {"player1": "Kyrian Jacquet", "player2": "Vilius Gaubas", "winner": "Kyrian Jacquet", "score": "6-3 6-4 7-6"},
    {"player1": "Adrian Mannarino", "player2": "Titouan Droguet", "winner": "Adrian Mannarino", "score": "6-2 6-4 6-1"},
    {"player1": "Benjamin Bonzi", "player2": "Gabriel Diallo", "winner": "Gabriel Diallo", "score": "1-6 4-6 7-6 7-5 6-3 RET"},
    {"player1": "Yannick Hanfmann", "player2": "Giovanni Mpetshi Perricard", "winner": "Yannick Hanfmann", "score": "6-7 6-7 7-6 6-2 6-3"},
    {"player1": "Sho Shimabukuro", "player2": "Jaime Faria", "winner": "Jaime Faria", "score": "7-6 6-3 6-7 2-6 6-3"},
    {"player1": "Jesper de Jong", "player2": "Rinky Hijikata", "winner": "Jesper de Jong", "score": "7-6 7-6 3-6 5-7 6-4"},
    {"player1": "Pablo Llamas Ruiz", "player2": "Zachary Svajda", "winner": "Zachary Svajda", "score": "6-1 6-2 6-4"},
    {"player1": "Valentin Royer", "player2": "Harry Wendelken", "winner": "Valentin Royer", "score": "4-6 6-3 6-3 6-3"},
    {"player1": "Jaume Munar", "player2": "Francisco Cerundolo", "winner": "Jaume Munar", "score": "6-1 6-4 6-3"},
    {"player1": "Alex Michelsen", "player2": "Jacob Fearnley", "winner": "Jacob Fearnley", "score": "3-6 4-6 6-2 6-3 6-2"},
    {"player1": "Damir Dzumhur", "player2": "Arthur Fery", "winner": "Arthur Fery", "score": "3-6 6-2 6-2 6-1"},

    # Ladies' Singles
    {"player1": "Taylor Townsend", "player2": "Iga Swiatek", "winner": "Iga Swiatek", "score": "6-1 2-6 6-3"},
    {"player1": "Amanda Anisimova", "player2": "Lina Gjorcheska", "winner": "Amanda Anisimova", "score": "6-3 6-2"},
    {"player1": "Katie Boulter", "player2": "Tyra Caterina Grant", "winner": "Tyra Caterina Grant", "score": "6-4 6-2"},
    {"player1": "Jasmine Paolini", "player2": "Robin Montgomery", "winner": "Jasmine Paolini", "score": "0-6 6-4 7-5"},
    {"player1": "Kayla Day", "player2": "Madison Keys", "winner": "Madison Keys", "score": "6-7 7-5 6-4"},
    {"player1": "Tereza Valentova", "player2": "Karolina Pliskova", "winner": "Karolina Pliskova", "score": "6-3 6-4"},
    {"player1": "Iryna Shymanovich", "player2": "Viktorija Golubic", "winner": "Viktorija Golubic", "score": "6-2 2-6 6-1"},
    {"player1": "Anhelina Kalinina", "player2": "Kamilla Rakhimova", "winner": "Kamilla Rakhimova", "score": "4-6 6-4 7-5"},
    {"player1": "Kimberly Birrell", "player2": "Alina Korneeva", "winner": "Kimberly Birrell", "score": "6-3 0-6 6-2"},
    {"player1": "Beatriz Haddad Maia", "player2": "Maria Timofeeva", "winner": "Maria Timofeeva", "score": "6-3 6-2"},
    {"player1": "Petra Marcinko", "player2": "Sofia Kenin", "winner": "Sofia Kenin", "score": "7-6 7-6"},
    {"player1": "Maria Sakkari", "player2": "Clara Tauson", "winner": "Maria Sakkari", "score": "6-3 6-3"},
    {"player1": "Irina-Camelia Begu", "player2": "Katie Swan", "winner": "Katie Swan", "score": "6-4 6-4"},
    {"player1": "Talia Gibson", "player2": "Marie Bouzkova", "winner": "Marie Bouzkova", "score": "6-1 3-6 6-2"},
    {"player1": "Lois Boisson", "player2": "Elena Rybakina", "winner": "Elena Rybakina", "score": "6-4 1-6 6-3"},
    {"player1": "Elina Svitolina", "player2": "Daria Snigur", "winner": "Daria Snigur", "score": "7-5 6-2"},
    {"player1": "Ella Seidel", "player2": "Linda Noskova", "winner": "Linda Noskova", "score": "6-4 6-3"},
    {"player1": "Nadia Podoroska", "player2": "Marta Kostyuk", "winner": "Marta Kostyuk", "score": "6-1 6-2"},
    {"player1": "Diana Shnaider", "player2": "Eva Lys", "winner": "Diana Shnaider", "score": "7-5 6-1"},
    {"player1": "Sorana Cirstea", "player2": "Sara Bejlek", "winner": "Sorana Cirstea", "score": "6-1 7-6"},
    {"player1": "Ashlyn Krueger", "player2": "Donna Vekic", "winner": "Ashlyn Krueger", "score": "3-6 7-6 6-4"},
    {"player1": "Camila Osorio", "player2": "Simona Waltert", "winner": "Camila Osorio", "score": "6-2 6-1"},
    {"player1": "Polina Kudermetova", "player2": "Liudmila Samsonova", "winner": "Liudmila Samsonova", "score": "6-3 6-3"},
]


def normalize_name(name):
    if not name:
        return ""

    text = str(name)
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.lower().strip()
    text = text.replace("-", " ")
    text = re.sub(r"[^a-z0-9\s']", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def same_player(a, b):
    return normalize_name(a) == normalize_name(b)


def filter_history_before_cutoff(matches):
    filtered = []

    for match in matches:
        date = str(match.get("date") or "0")

        if date != "0" and date < CUTOFF_DATE:
            filtered.append(match)

    return filtered


def build_backtest_elo_store():
    print("LOADING HISTORICAL MATCHES FOR BACKTEST...")
    all_history = load_all_matches(2018, 2030)

    print("HISTORICAL MATCHES LOADED:", len(all_history))

    cutoff_history = filter_history_before_cutoff(all_history)

    print("HISTORICAL MATCHES BEFORE", CUTOFF_DATE, ":", len(cutoff_history))

    if not cutoff_history:
        raise Exception("NO CUTOFF HISTORY FOR BACKTEST")

    store = build_elo(cutoff_history)

    print("BACKTEST ELO STORE PLAYERS:", len(store))

    if len(store) < 200:
        raise Exception("TOO FEW BACKTEST ELO PLAYERS")

    return store


def make_prediction_for_match(match, elo_store):
    player1 = match["player1"]
    player2 = match["player2"]

    elo_prediction = predict(
        player1,
        player2,
        "Grass",
        elo_store,
    )

    prob1 = elo_prediction["probability_player1"]
    prob2 = elo_prediction["probability_player2"]

    if prob1 >= prob2:
        pick = player1
        opponent = player2
        probability = prob1
    else:
        pick = player2
        opponent = player1
        probability = prob2

    status = "WON" if same_player(pick, match["winner"]) else "LOST"

    return {
        "player1": player1,
        "player2": player2,
        "match": f"{player1} vs {player2}",
        "pick": pick,
        "opponent": opponent,
        "winner": match["winner"],
        "score": match["score"],
        "probability": round(probability, 3),
        "status": status,
        "elo_found_player1": elo_prediction.get("elo_found_player1"),
        "elo_found_player2": elo_prediction.get("elo_found_player2"),
        "elo_player1": round(elo_prediction.get("elo_player1", 1500), 1),
        "elo_player2": round(elo_prediction.get("elo_player2", 1500), 1),
        "elo_matches_player1": elo_prediction.get("elo_matches_player1"),
        "elo_matches_player2": elo_prediction.get("elo_matches_player2"),
        "model": elo_prediction.get("model"),
    }


def summarize(rows):
    total = len(rows)
    won = len([r for r in rows if r["status"] == "WON"])
    lost = len([r for r in rows if r["status"] == "LOST"])

    hit_rate = round(won / total, 3) if total else 0

    found_both = len([
        r for r in rows
        if r.get("elo_found_player1") and r.get("elo_found_player2")
    ])

    max_probability = max([r["probability"] for r in rows], default=0)
    avg_probability = round(
        sum([r["probability"] for r in rows]) / total,
        3
    ) if total else 0

    return {
        "total": total,
        "won": won,
        "lost": lost,
        "hit_rate": hit_rate,
        "elo_found_both": found_both,
        "max_probability": max_probability,
        "avg_probability": avg_probability,
    }


def percent(value):
    try:
        return f"{float(value) * 100:.1f}%"
    except Exception:
        return "-"


def render_html(rows, summary):
    body = ""

    if not rows:
        body = """
<tr>
<td colspan="9">No rows available.</td>
</tr>
"""
    else:
        for i, row in enumerate(rows, 1):
            body += f"""
<tr>
<td>#{i}</td>
<td>{row["pick"]}</td>
<td>{row["opponent"]}</td>
<td>{percent(row["probability"])}</td>
<td>{row["status"]}</td>
<td>{row["winner"]}</td>
<td>{row["score"]}</td>
<td>{row["elo_found_player1"]} / {row["elo_found_player2"]}</td>
<td>{row["elo_player1"]} / {row["elo_player2"]}</td>
</tr>
"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Retro Backtest Wimbledon 2026-06-30</title>
<style>
body {{
    background: #160b0b;
    color: #ffffff;
    font-family: Arial, Helvetica, sans-serif;
    padding: 24px;
}}
h1 {{
    font-size: 38px;
    margin-bottom: 8px;
}}
.disclaimer {{
    color: #c7c7c7;
    font-size: 12px;
    margin-bottom: 24px;
}}
.summary {{
    background: #201313;
    padding: 14px 18px;
    border-radius: 10px;
    max-width: 420px;
    margin-bottom: 28px;
}}
table {{
    width: 100%;
    border-collapse: collapse;
}}
th, td {{
    border-bottom: 1px solid #3a2525;
    padding: 10px;
    text-align: left;
    vertical-align: top;
}}
th {{
    color: #f3f3f3;
}}
tr:hover {{
    background: #2a1616;
}}
</style>
</head>
<body>

<h1>Retro Backtest Wimbledon 2026-06-30</h1>
<div class="disclaimer">{DISCLAIMER}</div>

<div class="summary">
<h2>Summary</h2>
<p>Total: {summary["total"]}</p>
<p>Won: {summary["won"]}</p>
<p>Lost: {summary["lost"]}</p>
<p>Hit rate: {summary["hit_rate"] * 100:.1f}%</p>
<p>ELO found both: {summary["elo_found_both"]}</p>
<p>Avg probability: {percent(summary["avg_probability"])}</p>
<p>Max probability: {percent(summary["max_probability"])}</p>
</div>

<table>
<thead>
<tr>
<th>#</th>
<th>Pick</th>
<th>Opponent</th>
<th>Win %</th>
<th>Status</th>
<th>Winner</th>
<th>Score</th>
<th>ELO found</th>
<th>ELO</th>
</tr>
</thead>
<tbody>
{body}
</tbody>
</table>

</body>
</html>
"""


def run():
    os.makedirs(OUT_DIR, exist_ok=True)

    elo_store = build_backtest_elo_store()

    rows = [
        make_prediction_for_match(match, elo_store)
        for match in RESULTS
    ]

    rows.sort(key=lambda x: x["probability"], reverse=True)

    summary = summarize(rows)

    output = {
        "date": DATE,
        "mode": "retro_backtest_with_cutoff",
        "cutoff_date": CUTOFF_DATE,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": summary,
        "rows": rows,
    }

    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    with open(OUT_HTML, "w", encoding="utf-8") as f:
        f.write(render_html(rows, summary))

    print("WROTE", OUT_JSON)
    print("WROTE", OUT_HTML)
    print("SUMMARY:", summary)


if __name__ == "__main__":
    run()
