import json
import os
from datetime import datetime, timezone


OUT_DIR = "public/lab_last7"
OUT_JSON = f"{OUT_DIR}/index.json"
OUT_HTML = f"{OUT_DIR}/index.html"

DISCLAIMER = (
    "The data generated by the Backstage Talks STAT model is for statistical "
    "and informational purposes only."
)


def run():
    os.makedirs(OUT_DIR, exist_ok=True)

    output = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "mode": "temporarily_disabled",
        "status": "SKIPPED",
        "reason": (
            "Last 7 Days Retro Lab is temporarily disabled so the daily workflow "
            "can continue. Core predictions, odds snapshots, PLAY candidates, "
            "history tracking and pages are not affected."
        ),
        "elo_only_summary": {
            "total": 0,
            "won": 0,
            "lost": 0,
            "hit_rate": 0,
        },
        "elo_form_summary": {
            "total": 0,
            "won": 0,
            "lost": 0,
            "hit_rate": 0,
        },
        "elo_only_rows": [],
        "elo_form_rows": [],
    }

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Last 7 Days Retro Lab</title>
<style>
body {{
    background: #160b0b;
    color: #ffffff;
    font-family: Arial, Helvetica, sans-serif;
    padding: 24px;
}}
h1 {{
    font-size: 38px;
    margin-bottom: 8px;
}}
.disclaimer {{
    color: #c7c7c7;
    font-size: 12px;
    margin-bottom: 24px;
}}
.card {{
    background: #201313;
    padding: 18px;
    border-radius: 10px;
    max-width: 760px;
}}
</style>
</head>
<body>

<h1>Last 7 Days Retro Lab</h1>
<div class="disclaimer">{DISCLAIMER}</div>

<div class="card">
<h2>Temporarily disabled</h2>
<p>This diagnostic lab is temporarily skipped so the daily workflow can continue.</p>
<p>Core predictions, odds snapshots, PLAY candidates, history tracking and website outputs are not affected.</p>
<p>Generated at: {output["generated_at"]}</p>
</div>

</body>
</html>
"""

    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    with open(OUT_HTML, "w", encoding="utf-8") as f:
        f.write(html)

    print("Last 7 Days Retro Lab temporarily disabled.")
    print("WROTE", OUT_JSON)
    print("WROTE", OUT_HTML)


if __name__ == "__main__":
    run()
