import json
import os
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo

from sackmann_loader import load_all_matches
from elo_engine import build_elo, predict
from form_engine import build_form_store, get_player_form, calculate_form_adjustment


LOCAL_TZ = ZoneInfo("Europe/Bratislava")

OUT_DIR = "public/lab_last7"
OUT_JSON = f"{OUT_DIR}/index.json"
OUT_HTML = f"{OUT_DIR}/index.html"

DISCLAIMER = (
    "The data generated by the Backstage Talks STAT model is for statistical "
    "and informational purposes only."
)


def today_local():
    return datetime.now(LOCAL_TZ).date()


def yyyymmdd(date_obj):
    return date_obj.strftime("%Y%m%d")


def date_range_last_7_completed_days():
    today = today_local()
    end = today - timedelta(days=1)
    start = end - timedelta(days=6)

    return yyyymmdd(start), yyyymmdd(end)


def normalize_name(name):
    from elo_engine import normalize
    return normalize(name)


def same_player(a, b):
    return normalize_name(a) == normalize_name(b)


def clamp(value, low, high):
    return max(low, min(high, value))


def filter_matches_between(matches, start_date, end_date):
    output = []

    for match in matches:
        date = str(match.get("date") or "0")

        if date != "0" and start_date <= date <= end_date:
            if match.get("player1") and match.get("player2") and match.get("winner"):
                output.append(match)

    return output


def filter_matches_before(matches, cutoff_date):
    output = []

    for match in matches:
        date = str(match.get("date") or "0")

        if date != "0" and date < cutoff_date:
            output.append(match)

    return output


def make_elo_only_prediction(match, elo_store):
    player1 = match["player1"]
    player2 = match["player2"]
    surface = match.get("surface", "Hard")

    elo_prediction = predict(player1, player2, surface, elo_store)

    prob1 = elo_prediction["probability_player1"]
    prob2 = elo_prediction["probability_player2"]

    if prob1 >= prob2:
        pick = player1
        opponent = player2
        probability = prob1
    else:
        pick = player2
        opponent = player1
        probability = prob2

    return {
        "model_type": "ELO_ONLY",
        "date": match.get("date"),
        "tournament": match.get("tournament"),
        "surface": surface,
        "player1": player1,
        "player2": player2,
        "match": f"{player1} vs {player2}",
        "pick": pick,
        "opponent": opponent,
        "winner": match.get("winner"),
        "probability": round(probability, 3),
        "base_probability": round(probability, 3),
        "form_adjustment": 0,
        "status": "WON" if same_player(pick, match.get("winner")) else "LOST",
        "elo_found_player1": elo_prediction.get("elo_found_player1"),
        "elo_found_player2": elo_prediction.get("elo_found_player2"),
        "elo_reliability_player1": elo_prediction.get("elo_reliability_player1"),
        "elo_reliability_player2": elo_prediction.get("elo_reliability_player2"),
        "elo_matches_player1": elo_prediction.get("elo_matches_player1"),
        "elo_matches_player2": elo_prediction.get("elo_matches_player2"),
    }


def make_elo_form_prediction(match, elo_store, form_store):
    player1 = match["player1"]
    player2 = match["player2"]
    surface = match.get("surface", "Hard")

    elo_prediction = predict(player1, player2, surface, elo_store)

    prob1 = elo_prediction["probability_player1"]

    form1 = get_player_form(form_store, player1, surface)
    form2 = get_player_form(form_store, player2, surface)

    adjustment_for_player1 = calculate_form_adjustment(
        pick_form=form1,
        opponent_form=form2,
    )

    adjusted_prob1 = clamp(
        prob1 + adjustment_for_player1["total_adjustment"],
        0.15,
        0.85,
    )

    adjusted_prob2 = 1 - adjusted_prob1

    if adjusted_prob1 >= adjusted_prob2:
        pick = player1
        opponent = player2
        probability = adjusted_prob1
    else:
        pick = player2
        opponent = player1
        probability = adjusted_prob2

    return {
        "model_type": "ELO_FORM",
        "date": match.get("date"),
        "tournament": match.get("tournament"),
        "surface": surface,
        "player1": player1,
        "player2": player2,
        "match": f"{player1} vs {player2}",
        "pick": pick,
        "opponent": opponent,
        "winner": match.get("winner"),
        "probability": round(probability, 3),
        "base_probability": round(max(prob1, 1 - prob1), 3),
        "form_adjustment": adjustment_for_player1,
        "status": "WON" if same_player(pick, match.get("winner")) else "LOST",
        "elo_found_player1": elo_prediction.get("elo_found_player1"),
        "elo_found_player2": elo_prediction.get("elo_found_player2"),
        "elo_reliability_player1": elo_prediction.get("elo_reliability_player1"),
        "elo_reliability_player2": elo_prediction.get("elo_reliability_player2"),
        "elo_matches_player1": elo_prediction.get("elo_matches_player1"),
        "elo_matches_player2": elo_prediction.get("elo_matches_player2"),
        "form_player1": form1,
        "form_player2": form2,
    }


def summarize_light(rows):
    total = len(rows)
    won = len([r for r in rows if r["status"] == "WON"])
    lost = len([r for r in rows if r["status"] == "LOST"])
    hit_rate = round(won / total, 3) if total else 0

    return {
        "total": total,
        "won": won,
        "lost": lost,
        "hit_rate": hit_rate,
    }


def summarize(rows):
    total = len(rows)
    won = len([r for r in rows if r["status"] == "WON"])
    lost = len([r for r in rows if r["status"] == "LOST"])

    hit_rate = round(won / total, 3) if total else 0

    found_rows = [
        r for r in rows
        if r.get("elo_found_player1") and r.get("elo_found_player2")
    ]

    found_total = len(found_rows)
    found_won = len([r for r in found_rows if r["status"] == "WON"])
    found_hit_rate = round(found_won / found_total, 3) if found_total else 0

    avg_probability = round(
        sum([r["probability"] for r in rows]) / total,
        3
    ) if total else 0

    max_probability = max([r["probability"] for r in rows], default=0)

    top1 = rows[:1]
    top3 = rows[:3]
    top5 = rows[:5]

    return {
        "total": total,
        "won": won,
        "lost": lost,
        "hit_rate": hit_rate,
        "elo_found_both": found_total,
        "elo_found_both_won": found_won,
        "elo_found_both_hit_rate": found_hit_rate,
        "avg_probability": avg_probability,
        "max_probability": max_probability,
        "top1": summarize_light(top1),
        "top3": summarize_light(top3),
        "top5": summarize_light(top5),
    }


def group_matches_by_date(matches):
    grouped = {}

    for match in matches:
        date = str(match.get("date") or "0")
        grouped.setdefault(date, []).append(match)

    return grouped


def percent(value):
    try:
        return f"{float(value) * 100:.1f}%"
    except Exception:
        return "-"


def render_summary(title, summary):
    return f"""
<div class="summary">
<h2>{title}</h2>
<p>Total: {summary["total"]}</p>
<p>Won: {summary["won"]}</p>
<p>Lost: {summary["lost"]}</p>
<p>Hit rate: {summary["hit_rate"] * 100:.1f}%</p>
<p>ELO found both: {summary["elo_found_both"]}</p>
<p>ELO-found-only hit rate: {summary["elo_found_both_hit_rate"] * 100:.1f}%</p>
<p>Avg probability: {percent(summary["avg_probability"])}</p>
<p>Max probability: {percent(summary["max_probability"])}</p>
<p>TOP1: {summary["top1"]["won"]}-{summary["top1"]["lost"]} ({summary["top1"]["hit_rate"] * 100:.1f}%)</p>
<p>TOP3: {summary["top3"]["won"]}-{summary["top3"]["lost"]} ({summary["top3"]["hit_rate"] * 100:.1f}%)</p>
<p>TOP5: {summary["top5"]["won"]}-{summary["top5"]["lost"]} ({summary["top5"]["hit_rate"] * 100:.1f}%)</p>
</div>
"""


def render_rows_table(title, rows):
    body = ""

    for i, row in enumerate(rows[:150], 1):
        form_adj = row.get("form_adjustment")

        if isinstance(form_adj, dict):
            form_adj_text = form_adj.get("total_adjustment")
        else:
            form_adj_text = form_adj

        body += f"""
<tr>
<td>#{i}</td>
<td>{row.get("date")}</td>
<td>{row.get("surface")}</td>
<td>{row.get("pick")}</td>
<td>{row.get("opponent")}</td>
<td>{percent(row.get("probability"))}</td>
<td>{percent(row.get("base_probability"))}</td>
<td>{form_adj_text}</td>
<td>{row.get("status")}</td>
<td>{row.get("winner")}</td>
<td>{row.get("elo_found_player1")} / {row.get("elo_found_player2")}</td>
</tr>
"""

    return f"""
<h2>{title}</h2>
<table>
<thead>
<tr>
<th>#</th>
<th>Date</th>
<th>Surface</th>
<th>Pick</th>
<th>Opponent</th>
<th>Final Win %</th>
<th>Base Win %</th>
<th>Form adj.</th>
<th>Status</th>
<th>Winner</th>
<th>ELO found</th>
</tr>
</thead>
<tbody>
{body}
</tbody>
</table>
"""


def render_html(start_date, end_date, elo_rows, form_rows, elo_summary, form_summary):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Last 7 Days Lab</title>
<style>
body {{
    background: #160b0b;
    color: #ffffff;
    font-family: Arial, Helvetica, sans-serif;
    padding: 24px;
}}
h1 {{
    font-size: 38px;
    margin-bottom: 8px;
}}
.disclaimer {{
    color: #c7c7c7;
    font-size: 12px;
    margin-bottom: 24px;
}}
.summary-grid {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(330px, 1fr));
    gap: 16px;
    margin-bottom: 28px;
}}
.summary {{
    background: #201313;
    padding: 14px 18px;
    border-radius: 10px;
}}
table {{
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 34px;
}}
th, td {{
    border-bottom: 1px solid #3a2525;
    padding: 10px;
    text-align: left;
    vertical-align: top;
}}
th {{
    color: #f3f3f3;
}}
tr:hover {{
    background: #2a1616;
}}
.note {{
    background: #251717;
    padding: 12px;
    border-radius: 8px;
    color: #dddddd;
    margin-bottom: 22px;
}}
</style>
</head>
<body>

<h1>Last 7 Days Retro Lab</h1>
<div class="disclaimer">{DISCLAIMER}</div>

<div class="note">
Backtest period: {start_date} → {end_date}. This evaluates match-winner accuracy using historical completed matches.
Odds-based PLAY profitability requires stored daily odds snapshots.
</div>

<div class="summary-grid">
{render_summary("ELO only", elo_summary)}
{render_summary("ELO + form", form_summary)}
</div>

{render_rows_table("ELO + form rows", form_rows)}
{render_rows_table("ELO only rows", elo_rows)}

</body>
</html>
"""


def run():
    os.makedirs(OUT_DIR, exist_ok=True)

    start_date, end_date = date_range_last_7_completed_days()

    print("LAST 7 LAB PERIOD:", start_date, end_date)

    all_history = load_all_matches(2018, 2030)

    test_matches = filter_matches_between(all_history, start_date, end_date)

    print("TEST MATCHES:", len(test_matches))

    grouped = group_matches_by_date(test_matches)

    elo_rows = []
    form_rows = []

    for date in sorted(grouped.keys()):
        print("PROCESSING DATE:", date, "MATCHES:", len(grouped[date]))

        training_matches = filter_matches_before(all_history, date)

        elo_store = build_elo(training_matches)
        form_store = build_form_store(training_matches)

        for match in grouped[date]:
    elo_rows.append(
        make_elo_only_prediction(match, elo_store)
    )

    form_rows.append(
        make_elo_form_prediction(match, elo_store, form_store)
    )

    elo_rows.sort(key=lambda x: x["probability"], reverse=True)
    form_rows.sort(key=lambda x: x["probability"], reverse=True)

for match in grouped[date]:
            elo_rows.append(
                make_elo_only_prediction(match, elo_store)
            )

            form_rows.append(
                make_elo_form_prediction(rm_store)
            )
        "period_end": end_date,
        "mode": "rolling_last_7_completed_days_retro_lab",
        "note": "Odds-based PLAY profitability requires stored daily odds snapshots.",
        "elo_only_summary": elo_summary,
        "elo_form_summary": form_summary,
        "elo_only_rows": elo_rows,
        "elo_form_rows": form_rows,
    }

    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    with open(OUT_HTML, "w", encoding="utf-8") as f:
        f.write(render_html(
            start_date=start_date,
            end_date=end_date,
            elo_rows=elo_rows,
            form_rows=form_rows,
            elo_summary=elo_summary,
            form_summary=form_summary,
        ))

    print("WROTE", OUT_JSON)
    print("WROTE", OUT_HTML)
    print("ELO SUMMARY:", elo_summary)
    print("FORM SUMMARY:", form_summary)


if __name__ == "__main__":
    run()
