write_link_hub () {
  remove_file_if_exists "public/$LINKS"
  mkdir -p "public/$LINKS"

  local HUB_FILE="public/$LINKS/index.html"

  cat > "$HUB_FILE" <<EOF
<!DOCTYPE html>
<html lang="sk">
<head>
<meta charset="UTF-8">
<title>BackstageTalks Tennis Links</title>
<meta name="robots" content="noindex,nofollow,noarchive">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
* {
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background: #160f0f;
  color: #f4f4f4;
  margin: 0;
  padding: 22px;
}

.container {
  max-width: 900px;
  margin: 0 auto;
}

h1 {
  font-size: 42px;
  line-height: 1.1;
  margin: 26px 0 24px;
}

.grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 14px;
}

.card {
  background: #211818;
  border: 1px solid #352727;
  border-radius: 16px;
  padding: 16px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
}

.label {
  font-weight: 700;
  font-size: 18px;
  color: #ffffff;
}

.open-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 42px;
  height: 42px;
  border-radius: 999px;
  background: #2d3f66;
  color: #ffffff;
  font-size: 20px;
  text-decoration: none;
  flex: 0 0 auto;
}

.open-icon:hover {
  background: #4162a3;
  text-decoration: none;
}

.footer {
  color: #888;
  margin-top: 26px;
  font-size: 14px;
}

@media (min-width: 760px) {
  .grid {
    grid-template-columns: 1fr 1fr;
  }
}
</style>
</head>
<body>
<div class="container">
<h1>BackstageTalks Tennis Links</h1>

<div class="grid">

<div class="card">
  <div class="label">TOP 7 web:</div>
  $BASE/$TOP_WEB/🔗</a>
</div>

<div class="card">
  <div class="label">TOP 7 RSS:</div>
  $BASE/$TOP_RSS.xml🔗</a>
</div>

<div class="card">
  <div class="label">TOP 7 výsledky web:</div>
  $BASE/$TOP_RESULTS_WEB/🔗</a>
</div>

<div class="card">
  <div class="label">TOP 7 výsledky RSS:</div>
  $BASE/$TOP_RESULTS_RSS.xml🔗</a>
</div>

<div class="card">
  <div class="label">ALL web:</div>
  $BASE/$ALL_WEB/🔗</a>
</div>

<div class="card">
  <div class="label">ALL RSS:</div>
  $BASE/$ALL_RSS.xml🔗</a>
</div>

<div class="card">
  <div class="label">ALL výsledky web:</div>
  $BASE/$ALL_RESULTS_WEB/🔗</a>
</div>

<div class="card">
  <div class="label">ALL výsledky RSS:</div>
  $BASE/$ALL_RESULTS_RSS.xml🔗</a>
</div>

</div>

<div class="footer">Generated by BackstageTalks Tennis workflow.</div>
</div>
</body>
</html>
EOF

  echo "LINK HUB: public/$LINKS/index.html"
}
