#!/usr/bin/env bash
set -euo pipefail

BASE="https://backstagetalks.github.io/tennis-backstage-talks"

LINKS="H4V34N1C3D4Y177"

SOURCE_MANIFEST="H4V34N1C3D4Y170"
SOURCE_AUDIT="H4V34N1C3D4Y171"

TOP_WEB="H4V34N1C3D4Y180"
TOP_RSS="H4V34N1C3D4Y181"

TOP_RESULTS_WEB="H4V34N1C3D4Y182"
TOP_RESULTS_RSS="H4V34N1C3D4Y183"

ALL_WEB="H4V34N1C3D4Y184"
ALL_RSS="H4V34N1C3D4Y185"

ALL_RESULTS_WEB="H4V34N1C3D4Y186"
ALL_RESULTS_RSS="H4V34N1C3D4Y187"


remove_file_if_exists () {
  local TARGET="${1:-}"

  if [ -n "$TARGET" ] && [ -f "$TARGET" ]; then
    rm -f "$TARGET"
    echo "REMOVED FILE: $TARGET"
  fi
}


write_placeholder_html () {
  local FILE="${1:-}"
  local TITLE="${2:-BackstageTalks}"
  local MESSAGE="${3:-Content is not available yet.}"

  mkdir -p "$(dirname "$FILE")"

  cat > "$FILE" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>$TITLE</title>
<meta name="robots" content="noindex,nofollow,noarchive">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body {
  font-family: Arial, sans-serif;
  background: #160f0f;
  color: #f4f4f4;
  margin: 0;
  padding: 40px;
}
.container {
  max-width: 760px;
  margin: 0 auto;
}
h1 {
  font-size: 34px;
}
p {
  color: #cfcfcf;
  font-size: 18px;
}
</style>
</head>
<body>
<div class="container">
<h1>$TITLE</h1>
<p>$MESSAGE</p>
</div>
</body>
</html>
EOF
}


write_neutral_html () {
  local FILE="${1:-}"

  write_placeholder_html "$FILE" "BackstageTalks" "No public content available."
}


write_neutral_rss () {
  local FILE="${1:-}"
  local TITLE="${2:-BackstageTalks}"

  mkdir -p "$(dirname "$FILE")"

  cat > "$FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>$TITLE</title>
<link>$BASE/</link>
<description>No public content available</description>
</channel>
</rss>
EOF
}


copy_page_alias () {
  local SRC="${1:-}"
  local ALIAS="${2:-}"
  local TITLE="${3:-BackstageTalks}"

  remove_file_if_exists "public/$ALIAS"
  mkdir -p "public/$ALIAS"

  if [ -f "$SRC" ]; then
    cp "$SRC" "public/$ALIAS/index.html"
    echo "PAGE ALIAS: $SRC -> public/$ALIAS/index.html"
  else
    write_placeholder_html "public/$ALIAS/index.html" "$TITLE" "Content will be generated by the next daily run."
    echo "PAGE PLACEHOLDER: public/$ALIAS/index.html"
  fi
}


copy_rss_alias () {
  local SRC="${1:-}"
  local ALIAS="${2:-}"
  local TITLE="${3:-BackstageTalks RSS}"
  local PAGE_ALIAS="${4:-}"

  if [ -f "$SRC" ]; then
    cp "$SRC" "public/$ALIAS.xml"
    cp "$SRC" "public/$ALIAS"
    echo "RSS ALIAS: $SRC -> public/$ALIAS.xml"
  else
    cat > "public/$ALIAS.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>$TITLE</title>
<link>$BASE/$PAGE_ALIAS/</link>
<description>No content available yet</description>
</channel>
</rss>
EOF
    cp "public/$ALIAS.xml" "public/$ALIAS"
    echo "RSS PLACEHOLDER: public/$ALIAS.xml"
  fi
}


copy_json_alias () {
  local SRC="${1:-}"
  local ALIAS="${2:-}"
  local NAME="${3:-json}"

  if [ -f "$SRC" ]; then
    cp "$SRC" "public/$ALIAS"
    cp "$SRC" "public/$ALIAS.json"
    echo "JSON ALIAS: $SRC -> public/$ALIAS"
    echo "JSON ALIAS: $SRC -> public/$ALIAS.json"
  else
    cat > "public/$ALIAS" <<EOF
{
  "status": "PLACEHOLDER",
  "name": "$NAME",
  "message": "Content is not available yet."
}
EOF
    cp "public/$ALIAS" "public/$ALIAS.json"
    echo "JSON PLACEHOLDER: public/$ALIAS"
    echo "JSON PLACEHOLDER: public/$ALIAS.json"
  fi
}


add_link_card () {
  local FILE="${1:-}"
  local LABEL="${2:-Link}"
  local URL="${3:-#}"

  cat >> "$FILE" <<EOF
<div class="card">
  <div class="label">$LABEL</div>
  <a class="open-icon" href="$URL" target="_blank" rel="noopener noreferrer" title="Open link">🔗</a>
</div>

EOF
}


write_link_hub () {
  remove_file_if_exists "public/$LINKS"
  mkdir -p "public/$LINKS"

  local HUB_FILE="public/$LINKS/index.html"

  cat > "$HUB_FILE" <<EOF
<!DOCTYPE html>
<html lang="sk">
<head>
<meta charset="UTF-8">
<title>BackstageTalks Tennis Links</title>
<meta name="robots" content="noindex,nofollow,noarchive">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
* {
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  background: #160f0f;
  color: #f4f4f4;
  margin: 0;
  padding: 22px;
}

.container {
  max-width: 900px;
  margin: 0 auto;
}

h1 {
  font-size: 42px;
  line-height: 1.1;
  margin: 26px 0 24px;
}

.grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 14px;
}

.card {
  background: #211818;
  border: 1px solid #352727;
  border-radius: 16px;
  padding: 16px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
}

.label {
  font-weight: 700;
  font-size: 18px;
  color: #ffffff;
}

.open-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 42px;
  height: 42px;
  border-radius: 999px;
  background: #2d3f66;
  color: #ffffff;
  font-size: 20px;
  text-decoration: none;
  flex: 0 0 auto;
}

.open-icon:hover {
  background: #4162a3;
  text-decoration: none;
}

.footer {
  color: #888;
  margin-top: 26px;
  font-size: 14px;
}

@media (min-width: 760px) {
  .grid {
    grid-template-columns: 1fr 1fr;
  }
}
</style>
</head>
<body>
<div class="container">
<h1>BackstageTalks Tennis Links</h1>

<div class="grid">

EOF

  add_link_card "$HUB_FILE" "Source manifest:" "$BASE/$SOURCE_MANIFEST.json"
  add_link_card "$HUB_FILE" "Source audit:" "$BASE/$SOURCE_AUDIT.json"

  add_link_card "$HUB_FILE" "TOP 7 web:" "$BASE/$TOP_WEB/"
  add_link_card "$HUB_FILE" "TOP 7 RSS:" "$BASE/$TOP_RSS.xml"

  add_link_card "$HUB_FILE" "TOP 7 výsledky web:" "$BASE/$TOP_RESULTS_WEB/"
  add_link_card "$HUB_FILE" "TOP 7 výsledky RSS:" "$BASE/$TOP_RESULTS_RSS.xml"

  add_link_card "$HUB_FILE" "ALL web:" "$BASE/$ALL_WEB/"
  add_link_card "$HUB_FILE" "ALL RSS:" "$BASE/$ALL_RSS.xml"

  add_link_card "$HUB_FILE" "ALL výsledky web:" "$BASE/$ALL_RESULTS_WEB/"
  add_link_card "$HUB_FILE" "ALL výsledky RSS:" "$BASE/$ALL_RESULTS_RSS.xml"

  cat >> "$HUB_FILE" <<EOF
</div>

<div class="footer">Generated by BackstageTalks Tennis workflow.</div>
</div>
</body>
</html>
EOF

  echo "LINK HUB: public/$LINKS/index.html"
}


write_robots () {
  cat > public/robots.txt <<EOF
User-agent: *
Disallow: /tennis.xml
Disallow: /tennis_all.xml
Disallow: /results.xml
Disallow: /all_results.xml
Disallow: /all/
Disallow: /results/
Disallow: /all_results/
Disallow: /source_manifest.json
Disallow: /source_audit.json
EOF

  echo "ROBOTS: public/robots.txt"
}


echo "===== PUBLISH LINKS / ALIASES WITH BASH ====="

mkdir -p public

copy_json_alias "public/source_manifest.json" "$SOURCE_MANIFEST" "source_manifest"
copy_json_alias "public/source_audit.json" "$SOURCE_AUDIT" "source_audit"

copy_page_alias "public/index.html" "$TOP_WEB" "BackstageTalks Tennis TOP 7"
copy_rss_alias "public/tennis.xml" "$TOP_RSS" "BackstageTalks Tennis TOP 7 RSS" "$TOP_WEB"

copy_page_alias "public/results/index.html" "$TOP_RESULTS_WEB" "BackstageTalks Tennis TOP 7 Results"
copy_rss_alias "public/results.xml" "$TOP_RESULTS_RSS" "index.html" "$ALL_WEB" "BackstageTalks Tennis ALL"
copy_rss_alias "public/tennis_all.xml" "$ALL_RSS" "BackstageTalks Tennis ALL RSS" "$ALL_WEB"

copy_page_alias "public/all_results/index.html" "$ALL_RESULTS_WEB" "BackstageTalks Tennis ALL Results"
copy_rss_alias "public/all_results.xml" "$ALL_RESULTS_RSS" "BackstageTalks Tennis ALL Results RSS" "$ALL_RESULTS_WEB"

write_link_hub
write_robots

echo "===== NEUTRALIZE PUBLIC ROOT PATHS ====="

write_neutral_html "public/index.html"
write_neutral_rss "public/tennis.xml" "BackstageTalks Tennis"
write_neutral_rss "public/tennis_all.xml" "BackstageTalks Tennis ALL"
write_neutral_rss "public/results.xml" "BackstageTalks Tennis Results"
write_neutral_rss "public/all_results.xml" "BackstageTalks Tennis ALL Results"

mkdir -p public/all public/results public/all_results

write_neutral_html "public/all/index.html"
write_neutral_html "public/results/index.html"
write_neutral_html "public/all_results/index.html"

cat > public/source_manifest.json <<EOF
{
  "status": "NO_PUBLIC_CONTENT",
  "message": "No public content available."
}
EOF

cat > public/source_audit.json <<EOF
{
  "status": "NO_PUBLIC_CONTENT",
  "message": "No public content available."
}
EOF

echo "===== FINAL PUBLIC FILES ====="
ls -R public
