import os
import re
import json
import shutil
from html import escape

BASE = "https://backstagetalks.github.io/tennis-backstage-talks/"

A = {
    "links": "H4V34N1C3D4Y177",
    "manifest": "H4V34N1C3D4Y170",
    "audit": "H4V34N1C3D4Y171",

    "top_web": "H4V34N1C3D4Y180",
    "top_rss": "H4V34N1C3D4Y181",

    "top_results_web": "H4V34N1C3D4Y182",
    "top_results_rss": "H4V34N1C3D4Y183",

    "all_web": "H4V34N1C3D4Y184",
    "all_rss": "H4V34N1C3D4Y185",

    "all_results_web": "H4V34N1C3D4Y186",
    "all_results_rss": "H4V34N1C3D4Y187",
}


def ensure_parent(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)


def read_text(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def write_text(path, text):
    ensure_parent(path)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def write_json(path, data):
    ensure_parent(path)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def remove_file(path):
    if os.path.isfile(path):
        os.remove(path)
        print("REMOVED", path)


def copy_if_exists(src, dst):
    if not os.path.exists(src):
        print("MISSING", src)
        return False

    ensure_parent(dst)
    shutil.copyfile(src, dst)
    print("COPIED", src, "->", dst)
    return True


def page(title, body):
    title_e = escape(str(title))

    return """<!DOCTYPE html>
<html lang="sk">
<head>
<meta charset="UTF-8">
<title>""" + title_e + """</title>
<meta name="robots" content="noindex,nofollow,noarchive">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
*{box-sizing:border-box}
body{
    font-family:Arial,sans-serif;
    background:#160f0f;
    color:#f4f4f4;
    margin:0;
    padding:22px;
}
.container{
    max-width:1000px;
    margin:0 auto;
}
h1{
    font-size:42px;
    line-height:1.1;
    margin:26px 0 24px;
}
p{
    color:#cfcfcf;
    font-size:18px;
}
.grid{
    display:grid;
    grid-template-columns:1fr;
    gap:14px;
}
.link-card{
    background:#211818;
    border:1px solid #352727;
    border-radius:16px;
    padding:16px;
}
.label{
    font-weight:700;
    font-size:18px;
    margin-bottom:8px;
    color:#fff;
}
a{
    color:#8db7ff;
    word-break:break-all;
    font-size:16px;
    text-decoration:none;
}
a:hover{
    text-decoration:underline;
}
.footer{
    color:#888;
    margin-top:26px;
    font-size:14px;
}
@media(min-width:760px){
    .grid{grid-template-columns:1fr 1fr}
}
</style>
</head>
<body>
<div class="container">
<h1>""" + title_e + """</h1>
""" + body + """
</div>
</body>
</html>
"""


def neutral_html():
    return page("BackstageTalks", "<p>No public content available.</p>")


def neutral_rss(title):
    return """<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>""" + escape(str(title)) + """</title>
<link>""" + BASE + """</link>
<description>No public content available</description>
</channel>
</rss>
"""


def rss_placeholder(title, link_alias):
    return """<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>""" + escape(str(title)) + """</title>
<link>""" + BASE + link_alias + """/</link>
<description>No content available yet</description>
</channel>
</rss>
"""


def publish_html(src, alias, title):
    remove_file("public/" + alias)

    dst = "public/" + alias + "/index.html"

    if os.path.exists(src):
        write_text(dst, read_text(src))
        print("HTML", dst)
    else:
        write_text(
            dst,
            page(title, "<p>Content will be generated by the next daily run.</p>")
        )
        print("HTML PLACEHOLDER", dst)


def rewrite_links(xml, link):
    return re.sub(
        r"<link>.*?</link>",
        "<link>" + link + "</link>",
        xml,
        flags=re.DOTALL
    )


def publish_rss(src, alias, page_alias, title):
    if os.path.exists(src):
        xml = rewrite_links(read_text(src), BASE + page_alias + "/")
    else:
        xml = rss_placeholder(title, page_alias)

    write_text("public/" + alias + ".xml", xml)
    write_text("public/" + alias, xml)

    print("RSS", alias)


def write_hub():
    remove_file("public/" + A["links"])

    links = [
        ("Source manifest:", BASE + A["manifest"]),
        ("Source audit:", BASE + A["audit"]),

        ("TOP 7 web:", BASE + A["top_web"] + "/"),
        ("TOP 7 RSS:", BASE + A["top_rss"] + ".xml"),

        ("TOP 7 výsledky web:", BASE + A["top_results_web"] + "/"),
        ("TOP 7 výsledky RSS:", BASE + A["top_results_rss"] + ".xml"),

        ("ALL web:", BASE + A["all_web"] + "/"),
        ("ALL RSS:", BASE + A["all_rss"] + ".xml"),

        ("ALL výsledky web:", BASE + A["all_results_web"] + "/"),
        ("ALL výsledky RSS:", BASE + A["all_results_rss"] + ".xml"),
    ]

    cards = []

    for label, url in links:
        cards.append(
            '<div class="link-card">'
            '<div class="label">' + escape(str(label)) + '</div>'
            '<a href="' + escape(str(url)) + '" target="_blank" rel="noopener noreferrer">'
            + escape(str(url)) +
            '</a>'
            '</div>'
        )

    body = (
        '<div class="grid">'
        + "\n".join(cards)
        + '</div>'
        '<div class="footer">Generated by BackstageTalks Tennis workflow.</div>'
    )

    write_text(
        "public/" + A["links"] + "/index.html",
        page("BackstageTalks Tennis Links", body)
    )

    print("HUB", "public/" + A["links"] + "/index.html")


def write_robots():
    lines = [
        "User-agent: *",
        "Disallow: /tennis.xml",
        "       "Disallow: /results.xml",
        "Disallow: /all_results.xml",
        "Disallow: /all/",
        "Disallow: /results/",
        "Disallow: /all_results/",
        "Disallow: /source_manifest.json",
        "Disallow: /source_audit.json",
        "",
    ]

    write_text("public/robots.txt", "\n".join(lines))


def publish_aliases():
    os.makedirs("public", exist_ok=True)

    if not copy_if_exists("public/source_manifest.json", "public/" + A["manifest"]):
        write_json(
            "public/" + A["manifest"],
            {"status": "PLACEHOLDER", "name": "source_manifest"}
        )

    if not copy_if_exists("public/source_audit.json", "public/" + A["audit"]):
        write_json(
            "public/" + A["audit"],
            {"status": "PLACEHOLDER", "name": "source_audit"}
        )

    publish_html(
        "public/index.html",
        A["top_web"],
        "BackstageTalks Tennis TOP 7"
    )

    publish_rss(
        "public/tennis.xml",
        A["top_rss"],
        A["top_web"],
        "BackstageTalks Tennis TOP 7 RSS"
    )

    publish_html(
        "public/results/index.html",
        A["top_results_web"],
        "BackstageTalks Tennis TOP 7 Results"
    )

    publish_rss(
        "public/results.xml",
        A["top_results_rss"],
        A["top_results_web"],
        "BackstageTalks Tennis TOP 7 Results RSS"
    )

    publish_html(
        "public/all/index.html",
        A["all_web"],
        "BackstageTalks Tennis ALL"
    )

    publish_rss(
        "public/tennis_all.xml",
        A["all_rss"],
        A["all_web"],
        "BackstageTalks Tennis ALL RSS"
    )

    publish_html(
        "public/all_results/index.html",
        A["all_results_web"],
        "BackstageTalks Tennis ALL Results"
    )

    publish_rss(
        "public/all_results.xml",
        A["all_results_rss"],
        A["all_results_web"],
        "BackstageTalks Tennis ALL Results RSS"
    )

    write_hub()
    write_robots()

    # Neutralize old public outputs after private aliases are created.
    write_text("public/index.html", neutral_html())
    write_text("public/tennis.xml", neutral_rss("BackstageTalks Tennis"))
    write_text("public/tennis_all.xml", neutral_rss("BackstageTalks Tennis ALL"))
    write_text("public/results.xml", neutral_rss("BackstageTalks Tennis Results"))
    write_text("public/all_results.xml", neutral_rss("BackstageTalks Tennis ALL Results"))

    os.makedirs("public/all", exist_ok=True)
    os.makedirs("public/results", exist_ok=True)
    os.makedirs("public/all_results", exist_ok=True)

    write_text("public/all/index.html", neutral_html())
    write_text("public/results/index.html", neutral_html())
    write_text("public/all_results/index.html", neutral_html())

    write_json("public/source_manifest.json", {"status": "NO_PUBLIC_CONTENT"})
    write_json("public/source_audit.json", {"status": "NO_PUBLIC_CONTENT"})

    print("PRIVATE ALIASES GENERATED")


if __name__ == "__main__":
    publish_aliases()
