#!/usr/bin/env bash
set -euo pipefail

BASE="https://backstagetalks.github.io/tennis-backstage-talks"

LINKS="H4V34N1C3D4Y177"

SOURCE_MANIFEST="H4V34N1C3D4Y170"
SOURCE_AUDIT="H4V34N1C3D4Y171"

TOP_WEB="H4V34N1C3D4Y180"
TOP_RSS="H4V34N1C3D4Y181"

TOP_RESULTS_WEB="H4V34N1C3D4Y182"
TOP_RESULTS_RSS="H4V34N1C3D4Y183"

ALL_WEB="H4V34N1C3D4Y184"
ALL_RSS="H4V34N1C3D4Y185"

ALL_RESULTS_WEB="H4V34N1C3D4Y186"
ALL_RESULTS_RSS="H4V34N1C3D4Y187"

mkdir -p public

write_placeholder_html () {
  FILE="$1"
  TITLE="$2"
  MESSAGE="$3"

  mkdir -p "$(dirname "$FILE")"

  cat > "$FILE" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>$TITLE</title>
<meta name="robots" content="noindex,nofollow,noarchive">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body {
  font-family: Arial, sans-serif;
  background: #160f0f;
  color: #f4f4f4;
  margin: 0;
  padding: 40px;
}
.container {
  max-width: 760px;
  margin: 0 auto;
}
h1 {
  font-size: 34px;
}
p {
  color: #cfcfcf;
  font-size: 18px;
}
</style>
</head>
<body>
<div class="container">
<h1>$TITLE</h1>
<p>$MESSAGE</p>
</div>
</body>
</html>
EOF
}

write_neutral_html () {
  FILE="$1"
  write_placeholder_html "$FILE" "BackstageTalks" "No public content available."
}

write_neutral_rss () {
  FILE="$1"
  TITLE="$2"

  mkdir -p "$(dirname "$FILE")"

  cat > "$FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>$TITLE</title>
<link>$BASE/</link>
<description>No public content available</description>
</channel>
</rss>
EOF
}

copy_page_alias () {
  SRC="$1"
  ALIAS="$2"
  TITLE="$3"

  rm -f "public/$ALIAS"
  mkdir -p "public/$ALIAS"

  if [ -f "$SRC" ]; then
    cp "$SRC" "public/$ALIAS/index.html"
    echo "PAGE ALIAS: $SRC -> public/$ALIAS/index.html"
  else
    write_placeholder_html "public/$ALIAS/index.html" "$TITLE" "Content will be generated by the next daily run."
    echo "PAGE PLACEHOLDER: public/$ALIAS/index.html"
  fi
}

copy_rss_alias () {
  SRC="$1"
  ALIAS="$2"
  TITLE="$3"
  PAGE_ALIAS="$4"

  if [ -f "$SRC" ]; then
    cp "$SRC" "public/$ALIAS.xml"
    cp "$SRC" "public/$ALIAS"
    echo "RSS ALIAS: $SRC -> public/$ALIAS.xml"
  else
    cat > "public/$ALIAS.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>$TITLE</title>
<link>$BASE/$PAGE_ALIAS/</link>
<description>No content available yet</description>
</channel>
</rss>
EOF
    cp "public/$ALIAS.xml" "public/$ALIAS"
    echo "RSS PLACEHOLDER: public/$ALIAS.xml"
  fi
}

copy_json_alias () {
  SRC="$1"
  ALIAS="$2"
  NAME="$3"

  if [ -f "$SRC" ]; then
    cp "$SRC" "public/$ALIAS"
    echo "JSON ALIAS: $SRC -> public/$ALIAS"
  else
    cat > "public/$ALIAS" <<EOF
{
  "status": "PLACEHOLDER",
  "name": "$NAME",
  "message": "Content is not available yet."
}
EOF
    echo "JSON PLACEHOLDER: public/$ALIAS"
  fi
}

write_link_hub () {
  rm -f "public/$LINKS"
  mkdir -p "public/$LINKS"

  cat > "public/$LINKS/index.html" <<EOF
<!DOCTYPE html>
<html lang="sk">
<head>
<meta charset="UTF-8">
<title>BackstageTalks Tennis Links</title>
<meta name="robots" content="noindex,nofollow,noarchive">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
* {
  box-sizing: border-box;
}
body {
  font-family: Arial, sans-serif;
  background: #160f0f;
  color: #f4f4f4;
  margin: 0;
  padding: 22px;
}
.container {
  max-width: 1000px;
  margin: 0 auto;
}
h1 {
  font-size: 42px;
  line-height: 1.1;
  margin: 26px 0 24px;
}
.grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 14px;
}
.card {
  background: #211818;
  border: 1px solid #352727;
  border-radius: 16px;
  padding: 16px;
}
.label {
  font-weight: 700;
  font-size: 18px;
  margin-bottom: 8px;
  color: #ffffff;
}
a {
  color: #8db7ff;
  word-break: break-all;
  font-size: 16px;
  text-decoration: none;
}
a:hover {
  text-decoration: underline;
}
.footer {
  color: #888;
  margin-top: 26px;
  font-size: 14px;
}
@media (min-width: 760px) {
  .grid {
    grid-template-columns: 1fr 1fr;
  }
}
</style>
</head>
<body>
<div class="container">
<h1>BackstageTalks Tennis Links</h1>

<div class="grid">

<div class="card">
<div class="label">Source manifest:</div>
$BASE/$SOURCE_MANIFEST$BASE/$SOURCE_MANIFEST</a>
</div>

<div class="card">
<div class="label">Source audit:</div>
$BASE/$SOURCE_AUDIT$BASE/$SOURCE_AUDIT</a>
</div>

<div class="card">
<div class="label">TOP 7 web:</div>
$BASE/$TOP_WEB/$BASE/$TOP_WEB/</a>
</div>

<div class="card">
<div class="label">TOP 7 RSS:</div>
$BASE/$TOP_RSS.xml$BASE/$TOP_RSS.xml</a>
</div>

<div class="card">
<div class="label">TOP 7 výsledky web:</div>
$BASE/$TOP_RESULTS_WEB/$BASE/$TOP_RESULTS_WEB/</a>
</div>

<div class="card">
<div class="label">TOP 7 výsledky RSS:</div>
$BASE/$TOP_RESULTS_RSS.xml$BASE/$TOP_RESULTS_RSS.xml</a>
</div>

<div class="card">
<div class="label">ALL web:</div>
$BASE/$ALL_WEB/$BASE/$ALL_WEB/</a>
</div>

<div class="card">
<div class="label">ALL RSS:</div>
$BASE/$ALL_RSS.xml$BASE/$ALL_RSS.xml</a>
</div>

<div class="card">
<div class="label">ALL výsledky web:</div>
$BASE/$ALL_RESULTS_WEB/$BASE/$ALL_RESULTS_WEB/</a>
</div>

<div class="card">
<div class="label">ALL výsledky RSS:</div>
$BASE/$ALL_RESULTS_RSS.xml$BASE/$ALL_RESULTS_RSS.xml</a>
</div>

</div>

<div class="footer">Generated by BackstageTalks Tennis workflow.</div>
</div>
</body>
</html>
EOF

  echo "LINK HUB: public/$LINKS/index.html"
}

write_robots () {
  cat > public/robots.txt <<EOF
User-agent: *
Disallow: /tennis.xml
Disallow: /tennis_all.xml
Disallow: /results.xml
Disallow: /all_results.xml
Disallow: /all/
Disallow: /results/
Disallow: /all_results/
Disallow: /source_manifest.json
Disallow: /source_audit.json
EOF
}

echo "===== PUBLISH LINKS / ALIASES WITH BASH ====="

copy_json_alias "public/source_manifest.json" "$SOURCE_MANIFEST" "source_manifest"
copy_json_alias "public/source_audit.json" "$SOURCE_AUDIT" "source_audit"

copy_page_alias "public/index.html" "$TOP_WEB" "BackstageTalks Tennis TOP 7"
copy_rss_alias "public/tennis.xml" "$TOP_RSS" "BackstageTalks Tennis TOP 7 RSS" "$TOP_WEB"

copy_page_alias "public/results/index.html" "$TOP_RESULTS_WEB" "BackstageTalks Tennis TOP 7 Results"
copy_rss_alias "public/results.xml" "$TOP_RESULTS_RSS" "BackstageTalks Tennis TOP 7 Results RSS" "$TOP_RESULTS_WEB"

copy_page_alias "public/all/index.html" "$ALL_WEB" "BackstageTalks Tennis ALL"
copy_rss_alias "public/tennis_all.xml" "$ALL_RSS" "BackstageTalks Tennis ALL RSS" "$ALL_WEB"

copy_page_alias "public/all_results/index.html" "$ALL_RESULTS_WEB" "BackstageTalks Tennis ALL Results"
copy_rss_alias "public/all_results.xml" "$ALL_RESULTS_RSS" "BackstageTalks Tennis ALL Results RSS" "$ALL_RESULTS_WEB"

write_link_hub
write_robots

echo "===== NEUTRALIZE PUBLIC ROOT PATHS ====="

write_neutral_html "public/index.html"
write_neutral_rss "public/tennis.xml" "BackstageTalks Tennis"
write_neutral_rss "public/tennis_all.xml" "BackstageTalks Tennis ALL"
write_neutral_rss "public/results.xml" "BackstageTalks Tennis Results"
write_neutral_rss "public/all_results.xml" "BackstageTalks Tennis ALL Results"

mkdir -p public/all public/results public/all_results

write_neutral_html "public/all/index.html"
write_neutral_html "public/results/index.html"
write_neutral_html "public/all_results/index.html"

cat > public/source_manifest.json <<EOF
{
  "status": "NO_PUBLIC_CONTENT",
  "message": "No public content available."
}
EOF

cat > public/source_audit.json <<EOF
{
  "status": "NO_PUBLIC_CONTENT",
  "message": "No public content available."
}
EOF

echo "===== FINAL PUBLIC FILES ====="
ls -R public
