import glob
import html
import json
import os
from datetime import datetime, timezone
from email.utils import format_datetime


DISCLAIMER = "The data generated by the Backstage Talks STAT model is for statistical and informational purposes only."


def latest_file(pattern):
    files = sorted(glob.glob(pattern), reverse=True)
    return files[0] if files else None


def load_json(path, default):
    if not path:
        return default

    if not os.path.exists(path):
        return default

    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_predictions():
    path = latest_file("public/predictions_*.json")
    data = load_json(path, [])

    print("TOP JSON:", path, len(data))
    return data[:7]


def percent(value):
    try:
        return f"{float(value) * 100:.1f}%"
    except Exception:
        return "-"


def fmt(value):
    if value is None:
        return "-"
    return str(value)


def opponent_of(prediction):
    if prediction.get("opponent"):
        return prediction.get("opponent")

    pick = prediction.get("pick")
    player1 = prediction.get("player1")
    player2 = prediction.get("player2")

    if pick == player1:
        return player2

    return player1


def match_time_of(prediction):
    return (
        prediction.get("time")
        or prediction.get("match_time")
        or prediction.get("match_time_raw")
        or "TBD"
    )


def render_sets_games_info(prediction):
    info = prediction.get("alternative_market_info") or {}

    if not isinstance(info, dict):
        return "INFO ONLY"

    most_likely_sets = info.get("most_likely_sets")
    sets_probability = info.get("sets_probability")
    sets_fair_odds = info.get("sets_fair_odds")
    expected_games = info.get("expected_games")
    games_lean = info.get("games_lean")

    lines = []

    if most_likely_sets:
        if sets_probability:
            try:
                lines.append(
                    f"Sets: {html.escape(str(most_likely_sets))} "
                    f"({float(sets_probability) * 100:.1f}%, fair odds {fmt(sets_fair_odds)})"
                )
            except Exception:
                lines.append(f"Sets: {html.escape(str(most_likely_sets))}")
        else:
            lines.append(f"Sets: {html.escape(str(most_likely_sets))}")

    if expected_games:
        lines.append(f"Expected games: {fmt(expected_games)}")

    if games_lean:
        lines.append(f"Games: {html.escape(str(games_lean))}")

    lines.append("INFO ONLY")

    return "<br>".join(lines)


def render_html(predictions):
    rows = ""

    if not predictions:
        rows = """
<tr>
<td colspan="7">No TOP picks available. TOP requires real odds &gt;= 1.50.</td>
</tr>
"""
    else:
        for i, prediction in enumerate(predictions, 1):
            pick = html.escape(str(prediction.get("pick", "-")))
            opponent = html.escape(str(opponent_of(prediction) or "-"))
            match_time = html.escape(str(match_time_of(prediction)))
            win = percent(prediction.get("probability"))
            odds = fmt(prediction.get("odds"))
            sets_info = render_sets_games_info(prediction)

            rows += f"""
<tr>
<td class="rank">#{i}</td>
<td class="pick"><strong>{pick} to<br>win</strong></td>
<td>{opponent}</td>
<td>{match_time}</td>
<td>{win}</td>
<td>{odds}</td>
<td class="info">{sets_info}</td>
</tr>
"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Backstage Talks Tennis Picks</title>
<style>
* {{
    box-sizing: border-box;
}}

body {{
    margin: 0;
    background: #160b0b;
    color: #ffffff;
    font-family: Arial, Helvetica, sans-serif;
    padding: 10px 8px 40px 8px;
}}

a {{
    color: inherit;
}}

.rss-pill {{
    display: inline-block;
    background: #2563eb;
    color: #ffffff;
    text-decoration: none;
    font-weight: 700;
    font-size: 14px;
    padding: 8px 13px;
    border-radius: 999px;
    margin-bottom: 26px;
}}

h1 {{
    font-size: 42px;
    line-height: 1.1;
    margin: 0 0 10px 0;
    font-weight: 800;
}}

.disclaimer {{
    color: #c7c7c7;
    font-size: 12px;
    margin-bottom: 22px;
}}

.subtitle {{
    font-size: 18px;
    color: #eeeeee;
    margin-bottom: 28px;
}}

.table-wrap {{
    width: 100%;
    overflow-x: auto;
}}

table {{
    width: 100%;
    border-collapse: separate;
    border-spacing: 0;
    background: #201313;
    border-radius: 10px;
    overflow: hidden;
}}

th {{
    font-size: 15px;
    color: #f3f3f3;
    text-align: left;
    padding: 14px 16px;
    border-bottom: 1px solid #3a2525;
}}

td {{
    font-size: 15px;
    vertical-align: top;
    padding: 14px 16px;
    border-bottom: 1px solid #332020;
}}

tr:last-child td {{
    border-bottom: none;
}}

.rank {{
    width: 45px;
    white-space: nowrap;
}}

.pick {{
    width: 220px;
}}

.info {{
    min-width: 230px;
    line-height: 1.35;
}}

@media (max-width: 800px) {{
    h1 {{
        font-size: 30px;
    }}

    th, td {{
        font-size: 14px;
        padding: 12px 10px;
    }}
}}
</style>
</head>
<body>

<a class="rss-pill" href="tennis.xml">RSS TOP</a>

<h1>Backstage Talks Tennis Picks</h1>
<div class="disclaimer">{DISCLAIMER}</div>
<div class="subtitle">Top model picks for the CET window 06:00 → 06:00 next day.</div>

<div class="table-wrap">
<table>
<thead>
<tr>
<th>#</th>
<th>Pick</th>
<th>Opponent</th>
<th>Match time</th>
<th>Win<br>%</th>
<th>Odds</th>
<th>Sets / Games info</th>
</tr>
</thead>
<tbody>
{rows}
</tbody>
</table>
</div>

</body>
</html>
"""


def render_rss(predictions):
    now = datetime.now(timezone.utc)

    items = ""

    for prediction in predictions:
        pick = str(prediction.get("pick", "-"))
        opponent = str(opponent_of(prediction) or "-")
        match_time = str(match_time_of(prediction))
        odds = fmt(prediction.get("odds"))
        win = percent(prediction.get("probability"))

        title = html.escape(f"{pick} to win vs {opponent}")
        description = html.escape(
            f"Pick: {pick} | Opponent: {opponent} | Match time: {match_time} | Odds: {odds} | Win probability: {win}"
        )

        items += f"""
<item>
<title>{title}</title>
<description>{description}</description>
<pubDate>{format_datetime(now)}</pubDate>
</item>
"""

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>Backstage Talks Tennis Picks</title>
<link>https://backstagetalks.github.io/tennis-backstage-talks/</link>
<description>Daily TOP tennis picks</description>
<lastBuildDate>{format_datetime(now)}</lastBuildDate>
{items}
</channel>
</rss>
"""


def run():
    os.makedirs("public", exist_ok=True)

    predictions = load_predictions()

    with open("public/index.html", "w", encoding="utf-8") as f:
        f.write(render_html(predictions))

    with open("public/tennis.xml", "w", encoding="utf-8") as f:
        f.write(render_rss(predictions))

    print("WROTE public/index.html")
    print("WROTE public/tennis.xml")


if __name__ == "__main__":
    run()
