def create_all_page(predictions):
    os.makedirs("public/all", exist_ok=True)

    sorted_predictions = sorted(
        predictions,
        key=lambda p: (
            str(p.get("match_start", "")),
            -float(p.get("probability", 0)),
        )
    )

    rows = ""

    for i, prediction in enumerate(sorted_predictions, start=1):
        pick = str(prediction.get("pick", "Unknown"))
        opponent = str(prediction.get("opponent", "Unknown"))
        probability = float(prediction.get("probability", 0))
        odds = prediction.get("odds", "")
        match_time = format_match_time(prediction.get("match_start", ""))
        player1 = prediction.get("player1", "")
        player2 = prediction.get("player2", "")

        rows += (
            "<tr>"
            f"<td>#{i}</td>"
            f"<td>{esc(pick)} to win</td>"
            f"<td>{esc(opponent)}</td>"
            f"<td>{esc(player1)} vs {esc(player2)}</td>"
            f"<td>{esc(match_time) if match_time else '-'}</td>"
            f"<td>{pct(probability)}%</td>"
            f"<td>{esc(odds)}</td>"
            "</tr>\n"
        )

    page = (
        "<!DOCTYPE html>\n"
        "<html lang='en'>\n"
        "<head>\n"
        "<meta charset='UTF-8'>\n"
        "<title>Backstage Talks Tennis Picks - RSS ALL</title>\n"
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
        f"{INDEX_CSS}\n"
        "</head>\n"
        "<body>\n"
        "<div class='container'>\n"
        "<span class='badge'>RSS ALL</span>\n"
        "<h1>Backstage Talks Tennis Picks - All Matches</h1>\n"
        "<p>All available model picks for the CET window 06:00 → 06:00 next day.</p>\n"
        "<div class='table-wrap'>\n"
        "<table>\n"
        "<thead>\n"
        "<tr>\n"
        "<th>#</th>\n"
        "<th>Pick</th>\n"
        "<th>Opponent</th>\n"
        "<th>Match</th>\n"
        "<th class='time-col'>Match time</th>\n"
        "<th>Win %</th>\n"
        "<th>Odds</th>\n"
        "</tr>\n"
        "</thead>\n"
        "<tbody>\n"
        f"{rows}\n"
        "</tbody>\n"
        "</table>\n"
        "</div>\n"
        "<p class='note'>Generated by BackstageTalks Stat Model for informational and statistical purposes only</p>\n"
        "</div>\n"
        "</body>\n"
        "</html>\n"
    )

    with open("public/all/index.html", "w", encoding="utf-8") as f:
        f.write(page)
