import glob
import html
import json
import os
from datetime import datetime, timezone
from email.utils import format_datetime


DISCLAIMER = "The data generated by the Backstage Talks STAT model is for statistical and informational purposes only."


def latest_file(pattern):
    files = sorted(glob.glob(pattern), reverse=True)
    return files[0] if files else None


def load_json(path, default):
    if not path or not os.path.exists(path):
        return default

    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_predictions():
    path = latest_file("public/predictions_*.json")
    data = load_json(path, [])

    print("TOP JSON:", path, len(data))
    return data[:7]


def load_debug():
    return load_json("public/debug_counts.json", {})


def percent(value):
    try:
        return f"{float(value) * 100:.1f}%"
    except Exception:
        return "-"


def fmt(value):
    if value is None:
        return "-"
    return str(value)


def opponent_of(prediction):
    if prediction.get("opponent"):
        return prediction.get("opponent")

    pick = prediction.get("pick")
    p1 = prediction.get("player1")
    p2 = prediction.get("player2")

    if pick == p1:
        return p2

    return p1


def render_debug(debug):
    if not debug:
        return "<p>No debug data available.</p>"

    return f"""
<div class="debug">
<strong>Debug:</strong><br>
ALL matches: {debug.get("all_count", 0)}<br>
TOP picks: {debug.get("top_count", 0)}<br>
Matches with odds: {debug.get("with_odds_count", 0)}<br>
Eligible odds >= 1.50: {debug.get("eligible_odds_1_50_count", 0)}<br>
Max probability: {debug.get("max_probability", 0)}
</div>
"""


def render_html(predictions, debug):
    rows = ""

    if not predictions:
        rows = """
<tr>
<td colspan="7">No TOP picks available. TOP requires real odds >= 1.50.</td>
</tr>
"""
    else:
        for i, p in enumerate(predictions, 1):
            pick = html.escape(str(p.get("pick", "-")))
            opponent = html.escape(str(opponent_of(p) or "-"))
            match_time = html.escape(str(p.get("time") or p.get("match_time_raw") or "TBD"))
            win = percent(p.get("probability"))
            odds = fmt(p.get("odds"))

            rows += f"""
<tr>
<td>{i}</td>
<td><strong>{pick} to win</strong></td>
<td>{opponent}</td>
<td>{match_time}</td>
<td>{win}</td>
<td>{odds}</td>
<td>INFO ONLY</td>
</tr>
"""

    debug_html = render_debug(debug)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Backstage Talks Tennis Picks</title>
<style>
body {{
    background: #1a0f0f;
    color: #ffffff;
    font-family: Arial, sans-serif;
    padding: 24px;
}}
h1 {{
    margin-bottom: 6px;
}}
.disclaimer {{
    color: #b8b8b8;
    font-size: 12px;
    margin-bottom: 22px;
}}
.debug {{
    background: #2a1616;
    padding: 12px;
    margin-bottom: 18px;
    border-radius: 8px;
    color: #dddddd;
}}
table {{
    border-collapse: collapse;
    width: 100%;
}}
th, td {{
    border-bottom: 1px solid #3a2828;
    padding: 10px;
    text-align: left;
}}
th {{
    color: #cccccc;
}}
tr:hover {{
    background: #2a1616;
}}
</style>
</head>
<body>
<h1>Backstage Talks Tennis Picks</h1>
<div class="disclaimer">{DISCLAIMER}</div>

{debug_html}

<table>
<thead>
<tr>
<th>#</th>
<th>Pick</th>
<th>Opponent</th>
<th>Match time</th>
<th>Win %</th>
<th>Odds</th>
<th>Sets / Games info</th>
</tr>
</thead>
<tbody>
{rows}
</tbody>
</table>
</body>
</html>
"""


def render_rss(predictions):
    now = datetime.now(timezone.utc)

    items = ""

    for p in predictions:
        pick = str(p.get("pick", "-"))
        opponent = str(opponent_of(p) or "-")
        match_time = str(p.get("time") or p.get("match_time_raw") or "TBD")
        odds = fmt(p.get("odds"))
        win = percent(p.get("probability"))

        title = html.escape(f"{pick} to win vs {opponent}")
        description = html.escape(
            f"Pick: {pick} | Opponent: {opponent} | Match time: {match_time} | Odds: {odds} | Win probability: {win}"
        )

        items += f"""
<item>
<title>{title}</title>
<description>{description}</description>
<pubDate>{format_datetime(now)}</pubDate>
</item>
"""

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>Backstage Talks Tennis Picks</title>
<link>https://backstagetalks.github.io/tennis-backstage-talks/</link>
<description>Daily TOP tennis picks</description>
<lastBuildDate>{format_datetime(now)}</lastBuildDate>
{items}
</channel>
</rss>
"""


def run():
    os.makedirs("public", exist_ok=True)

    predictions = load_predictions()
    debug = load_debug()

    with open("public/index.html", "w", encoding="utf-8") as f:
        f.write(render_html(predictions, debug))

    with open("public/tennis.xml", "w", encoding="utf-8") as f:
        f.write(render_rss(predictions))

    print("WROTE public/index.html")
    print("WROTE public/tennis.xml")


if __name__ == "__main__":
    run()
