import json
import os
import re
import unicodedata
from datetime import datetime, timezone


OUT_DIR = "public/selection_lab_wimbledon"
OUT_JSON = f"{OUT_DIR}/index.json"
OUT_HTML = f"{OUT_DIR}/index.html"

WIMBLEDON_BACKTEST_JSON = "public/backtest_2026-06-30/index.json"
WIMBLEDON_ALL_PREDICTIONS_JSON = "public/all_predictions_2026-06-30.json"

DISCLAIMER = (
    "The data generated by the Backstage Talks STAT model is for statistical "
    "and informational purposes only."
)


# Manual odds that we know from discussion.
# These are used only if stored daily prediction odds are not available.
# Keyed primarily by pick name.
MANUAL_PICK_ODDS = {
    "taylor fritz": 1.03,
    "alex de minaur": 1.22,
    "brandon nakashima": 1.29,
    "francisco cerundolo": 1.28,
}


VARIANTS = {
    "A_SIMPLE_60": {
        "description": "ELO found both + odds >= 1.50 + Win % >= 60",
        "min_probability": 0.60,
        "use_odds_band": False,
        "min_reliability": None,
    },
    "B_ODDS_BAND": {
        "description": "ELO found both + odds band threshold",
        "min_probability": None,
        "use_odds_band": True,
        "min_reliability": None,
    },
    "C_SIMPLE_60_RELIABILITY": {
        "description": "Simple 60 + min ELO reliability >= 0.30",
        "min_probability": 0.60,
        "use_odds_band": False,
        "min_reliability": 0.30,
    },
    "D_ODDS_BAND_RELIABILITY": {
        "description": "Odds band + min ELO reliability >= 0.30",
        "min_probability": None,
        "use_odds_band": True,
        "min_reliability": 0.30,
    },
}


def normalize_name(name):
    if not name:
        return ""

    text = str(name)
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.lower().strip()
    text = text.replace("-", " ")
    text = re.sub(r"[^a-z0-9\s']", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def load_json(path, default):
    if not os.path.exists(path):
        print("MISSING JSON:", path)
        return default

    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print("LOAD JSON ERROR:", path, e)
        return default


def player_pair_key(a, b):
    names = sorted([normalize_name(a), normalize_name(b)])
    return "::".join(names)


def build_prediction_odds_lookup():
    data = load_json(WIMBLEDON_ALL_PREDICTIONS_JSON, [])

    lookup = {}

    if not isinstance(data, list):
        return lookup

    for prediction in data:
        try:
            player1 = prediction.get("player1")
            player2 = prediction.get("player2")
            pick = prediction.get("pick")
            odds = prediction.get("odds")

            if not player1 or not player2 or not pick or odds is None:
                continue

            key = player_pair_key(player1, player2)

            lookup[key] = {
                "pick": pick,
                "odds": float(odds),
                "player1": player1,
                "player2": player2,
            }

        except Exception:
            continue

    return lookup


def get_manual_odds(row):
    pick = normalize_name(row.get("pick"))
    return MANUAL_PICK_ODDS.get(pick)


def enrich_row_with_odds(row, odds_lookup):
    player1 = row.get("player1")
    player2 = row.get("player2")

    row = dict(row)

    odds = row.get("odds")

    if odds is not None:
        try:
            row["odds"] = float(odds)
            row["odds_source_lab"] = "row"
            return row
        except Exception:
            row["odds"] = None

    key = player_pair_key(player1, player2)
    from_json = odds_lookup.get(key)

    if from_json:
        try:
            if normalize_name(from_json.get("pick")) == normalize_name(row.get("pick")):
                row["odds"] = float(from_json.get("odds"))
                row["odds_source_lab"] = "all_predictions_2026-06-30"
                return row
        except Exception:
            pass

    manual_odds = get_manual_odds(row)

    if manual_odds is not None:
        row["odds"] = float(manual_odds)
        row["odds_source_lab"] = "manual_override"
        return row

    row["odds"] = None
    row["odds_source_lab"] = None
    return row


def odds_band_required_probability(odds):
    if odds is None:
        return None

    try:
        odds = float(odds)
    except Exception:
        return None

    if odds < 1.50:
        return None

    if 1.50 <= odds <= 1.59:
        return 0.66

    if 1.60 <= odds <= 1.74:
        return 0.62

    if 1.75 <= odds <= 1.99:
        return 0.60

    if odds >= 2.00:
        return 0.58

    return None


def min_reliability(row):
    r1 = row.get("elo_reliability_player1")
    r2 = row.get("elo_reliability_player2")

    try:
        if r1 is None or r2 is None:
            return 0.0

        return min(float(r1), float(r2))
    except Exception:
        return 0.0


def is_elo_found_both(row):
    return bool(row.get("elo_found_player1")) and bool(row.get("elo_found_player2"))


def variant_passes(row, variant_config):
    probability = row.get("probability")
    odds = row.get("odds")

    try:
        probability = float(probability)
    except Exception:
        return False, "missing_probability"

    try:
        odds = float(odds)
    except Exception:
        return False, "missing_odds"

    if not is_elo_found_both(row):
        return False, "elo_missing"

    if odds < 1.50:
        return False, "odds_below_1_50"

    min_reliability_required = variant_config.get("min_reliability")

    if min_reliability_required is not None:
        if min_reliability(row) < min_reliability_required:
            return False, "low_reliability"

    if variant_config.get("use_odds_band"):
        required = odds_band_required_probability(odds)

        if required is None:
            return False, "odds_band_no_rule"

        if probability < required:
            return False, "below_odds_band_probability"

        return True, "passed_odds_band"

    min_probability = variant_config.get("min_probability")

    if min_probability is not None:
        if probability < min_probability:
            return False, "below_min_probability"

    return True, "passed_simple"


def profit_for_row(row):
    if row.get("status") == "WON":
        try:
            return round(float(row.get("odds")) - 1, 3)
        except Exception:
            return 0

    if row.get("status") == "LOST":
        return -1

    return 0


def summarize_rows(rows):
    total = len(rows)

    won = len([r for r in rows if r.get("status") == "WON"])
    lost = len([r for r in rows if r.get("status") == "LOST"])

    settled = won + lost

    hit_rate = round(won / settled, 3) if settled else 0

    profit = round(sum(profit_for_row(r) for r in rows), 3)
    roi = round(profit / settled, 3) if settled else 0

    odds_values = []

    for row in rows:
        try:
            if row.get("odds") is not None:
                odds_values.append(float(row.get("odds")))
        except Exception:
            continue

    avg_odds = round(sum(odds_values) / len(odds_values), 3) if odds_values else 0

    return {
        "total": total,
        "settled": settled,
        "won": won,
        "lost": lost,
        "hit_rate": hit_rate,
        "avg_odds": avg_odds,
        "profit_1u": profit,
        "roi": roi,
    }


def evaluate_variant(name, config, rows):
    candidate_rows = []

    rejected_reasons = {}

    for row in rows:
        passes, reason = variant_passes(row, config)

        if passes:
            candidate = dict(row)
            candidate["selection_reason"] = reason
            candidate_rows.append(candidate)
        else:
            rejected_reasons[reason] = rejected_reasons.get(reason, 0) + 1

    candidate_rows.sort(
        key=lambda r: (
            float(r.get("probability") or 0),
            min_reliability(r),
        ),
        reverse=True
    )

    top1 = candidate_rows[:1]
    top3 = candidate_rows[:3]
    top5 = candidate_rows[:5]

    return {
        "variant": name,
        "description": config.get("description"),
        "candidate_count": len(candidate_rows),
        "rejected_reasons": rejected_reasons,
        "top1_summary": summarize_rows(top1),
        "top3_summary": summarize_rows(top3),
        "top5_summary": summarize_rows(top5),
        "top5_rows": top5,
        "all_candidate_rows": candidate_rows,
    }


def load_backtest_rows():
    data = load_json(WIMBLEDON_BACKTEST_JSON, {})

    if not isinstance(data, dict):
        return []

    rows = data.get("rows", [])

    if not isinstance(rows, list):
        return []

    return rows


def percent(value):
    try:
        return f"{float(value) * 100:.1f}%"
    except Exception:
        return "-"


def fmt(value):
    if value is None:
        return "-"

    return str(value)


def render_summary_card(result):
    top1 = result["top1_summary"]
    top3 = result["top3_summary"]
    top5 = result["top5_summary"]

    return f"""
<div class="card">
<h2>{result["variant"]}</h2>
<p class="desc">{result["description"]}</p>
<p>Candidate count: {result["candidate_count"]}</p>

<h3>TOP1</h3>
<p>{top1["won"]}-{top1["lost"]} | Hit rate: {top1["hit_rate"] * 100:.1f}% | Profit: {top1["profit_1u"]}u | ROI: {top1["roi"] * 100:.1f}%</p>

<h3>TOP3</h3>
<p>{top3["won"]}-{top3["lost"]} | Hit rate: {top3["hit_rate"] * 100:.1f}% | Profit: {top3["profit_1u"]}u | ROI: {top3["roi"] * 100:.1f}%</p>

<h3>TOP5</h3>
<p>{top5["won"]}-{top5["lost"]} | Hit rate: {top5["hit_rate"] * 100:.1f}% | Avg odds: {top5["avg_odds"]} | Profit: {top5["profit_1u"]}u | ROI: {top5["roi"] * 100:.1f}%</p>
</div>
"""


def render_rows_table(title, rows):
    body = ""

    if not rows:
        body = """
<tr>
<td colspan="11">No rows.</td>
</tr>
"""
    else:
        for i, row in enumerate(rows, 1):
            body += f"""
<tr>
<td>#{i}</td>
<td>{fmt(row.get("pick"))}</td>
<td>{fmt(row.get("opponent"))}</td>
<td>{percent(row.get("probability"))}</td>
<td>{fmt(row.get("odds"))}</td>
<td>{fmt(row.get("status"))}</td>
<td>{fmt(row.get("winner"))}</td>
<td>{fmt(row.get("score"))}</td>
<td>{fmt(row.get("elo_found_player1"))} / {fmt(row.get("elo_found_player2"))}</td>
<td>{fmt(row.get("elo_reliability_player1"))} / {fmt(row.get("elo_reliability_player2"))}</td>
<td>{fmt(row.get("odds_source_lab"))}</td>
</tr>
"""

    return f"""
<h2>{title}</h2>
<table>
<thead>
<tr>
<th>#</th>
<th>Pick</th>
<th>Opponent</th>
<th>Win %</th>
<th>Odds</th>
<th>Status</th>
<th>Winner</th>
<th>Score</th>
<th>ELO found</th>
<th>Reliability</th>
<th>Odds source</th>
</tr>
</thead>
<tbody>
{body}
</tbody>
</table>
"""


def render_html(results, enriched_rows):
    cards = "\n".join(render_summary_card(result) for result in results)

    variant_tables = ""

    for result in results:
        variant_tables += render_rows_table(
            f"{result['variant']} - TOP5 rows",
            result["top5_rows"]
        )

    all_odds_rows = [
        row for row in enriched_rows
        if row.get("odds") is not None
    ]

    all_odds_rows.sort(
        key=lambda r: float(r.get("probability") or 0),
        reverse=True
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Selection Lab Wimbledon 2026-06-30</title>
<style>
body {{
    background: #160b0b;
    color: #ffffff;
    font-family: Arial, Helvetica, sans-serif;
    padding: 24px;
}}
h1 {{
    font-size: 38px;
    margin-bottom: 8px;
}}
.disclaimer {{
    color: #c7c7c7;
    font-size: 12px;
    margin-bottom: 24px;
}}
.grid {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(330px, 1fr));
    gap: 16px;
    margin-bottom: 30px;
}}
.card {{
    background: #201313;
    padding: 16px;
    border-radius: 10px;
}}
.card h2 {{
    margin-top: 0;
}}
.desc {{
    color: #cfcfcf;
    font-size: 13px;
}}
table {{
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 34px;
}}
th, td {{
    border-bottom: 1px solid #3a2525;
    padding: 10px;
    text-align: left;
    vertical-align: top;
}}
th {{
    color: #f3f3f3;
}}
tr:hover {{
    background: #2a1616;
}}
.note {{
    background: #251717;
    padding: 12px;
    border-radius: 8px;
    color: #dddddd;
    margin-bottom: 22px;
}}
</style>
</head>
<body>

<h1>Selection Lab Wimbledon 2026-06-30</h1>
<div class="disclaimer">{DISCLAIMER}</div>

<div class="note">
This lab evaluates PLAY-selection variants using the Wimbledon 2026-06-30 retro backtest rows.
Only rows with available odds can enter PLAY variants. Missing historical odds are not simulated.
</div>

<div class="grid">
{cards}
</div>

{render_rows_table("All rows with known odds", all_odds_rows)}

{variant_tables}

</body>
</html>
"""


def run():
    os.makedirs(OUT_DIR, exist_ok=True)

    raw_rows = load_backtest_rows()
    odds_lookup = build_prediction_odds_lookup()

    enriched_rows = [
        enrich_row_with_odds(row, odds_lookup)
        for row in raw_rows
    ]

    results = []

    for variant_name, variant_config in VARIANTS.items():
        results.append(
            evaluate_variant(
                name=variant_name,
                config=variant_config,
                rows=enriched_rows,
            )
        )

    output = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_backtest": WIMBLEDON_BACKTEST_JSON,
        "source_predictions_for_odds": WIMBLEDON_ALL_PREDICTIONS_JSON,
        "manual_pick_odds": MANUAL_PICK_ODDS,
        "variants": results,
        "enriched_rows": enriched_rows,
    }

    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    with open(OUT_HTML, "w", encoding="utf-8") as f:
        f.write(render_html(results, enriched_rows))

    print("WROTE", OUT_JSON)
    print("WROTE", OUT_HTML)

    for result in results:
        print(result["variant"], result["top5_summary"])


if __name__ == "__main__":
    run()
