# -*- coding: utf-8 -*-

import html
import os
import re
from datetime import datetime

import feedparser
import requests

# ============================================================
# TELEGRAM SECRETS
# ============================================================

BOT_TOKEN = os.getenv("TG_BOT_BTLKR")
CHAT_ID = os.getenv("TG_CHAT_ID")

if not BOT_TOKEN:
    raise ValueError("Missing GitHub secret: TG_BOT_BTLKR")
if not CHAT_ID:
    raise ValueError("Missing GitHub secret: TG_CHAT_ID")

# ============================================================
# RSS FEEDS
# ============================================================

CORQ_FEED_URL = "https://backstagetalks.github.io/tennis-backstage-talks/h4v34n1c3d4y185.xml"
THINQ_FEED_URL = "https://backstagetalks.github.io/tennis-backstage-talks/h4v34n1c3d4y186.xml"
CLOQ_FEED_URL = "https://backstagetalks.github.io/tennis-backstage-talks/tennis_cloq.xml"

RSS_FEEDS = [
    {
        "key": "corq",
        "url": CORQ_FEED_URL,
        "title": "TOP 7 | Corq Model",
        "pick_limit": 7,
    },
    {
        "key": "thinq",
        "url": THINQ_FEED_URL,
        "title": "TOP 7 | Thinq Model",
        "pick_limit": 7,
    },
    {
        "key": "cloq",
        "url": CLOQ_FEED_URL,
        "title": "TOP 7 | Cloq Model",
        "pick_limit": 7,
    },
    {
        "key": "free",
        "url": CORQ_FEED_URL,
        "title": "FREE",
        "pick_limit": 1,
    },
]

SELECTED_FEED = os.getenv("TG_FEED", "all").strip().lower()

# Cloq Telegram guard. The RSS should already be generated by Cloq logic,
# but this second layer keeps TG aligned with close-market rules.
CLOQ_MAX_MARKET_GAP = float(os.getenv("CLOQ_MAX_MARKET_GAP", "15.0"))
CLOQ_MIN_EDGE = float(os.getenv("CLOQ_MIN_EDGE", "2.0"))
CLOQ_MIN_WR = float(os.getenv("CLOQ_MIN_WR", "55.0"))
CLOQ_BANNED_MARKETS = {"CAUTION", "BEARISH"}

# ============================================================
# FUNCTIONS
# ============================================================

def clean_text(value):
    if not value:
        return ""
    value = html.unescape(str(value))
    value = re.sub(r"<br\s*/?>", "\n", value, flags=re.IGNORECASE)
    value = re.sub(r"</p\s*>", "\n", value, flags=re.IGNORECASE)
    value = re.sub(r"<[^>]+>", " ", value)
    value = re.sub(r"[ \t]+", " ", value)
    value = re.sub(r"\n\s*\n+", "\n", value)
    return value.strip()


def clean_one_line(value):
    return re.sub(r"\s+", " ", clean_text(value)).strip()


def extract_player(title):
    title = clean_one_line(title)
    if " to win vs " in title:
        return title.split(" to win vs ", 1)[0].strip()
    return title.strip()


def extract_probability(description):
    value = number("Win probability", description, percent=True)
    return value


def extract_odds(description):
    return number("Odds", description, percent=False)


def number(label, description, percent=False):
    description = clean_text(description)
    suffix = "%" if percent else ""
    match = re.search(
        re.escape(label) + r":\s*([+-]?[0-9]+(?:\.[0-9]+)?)" + re.escape(suffix),
        description,
        re.IGNORECASE,
    )
    return match.group(1) if match else None


def parse_float(value):
    try:
        if value is None or value == "":
            return None
        return float(str(value).replace(",", "."))
    except Exception:
        return None


def market_signal(description):
    text = clean_text(description)
    match = re.search(r"Market Signal:\s*([^\n]+)", text, re.IGNORECASE)
    if match:
        return clean_one_line(match.group(1)).upper()
    return ""


def normalized_market_gap_percent(odds_a, odds_b):
    try:
        a = float(odds_a)
        b = float(odds_b)
        if a <= 1.0 or b <= 1.0:
            return None
        imp_a = 1.0 / a
        imp_b = 1.0 / b
        total = imp_a + imp_b
        if total <= 0:
            return None
        return abs((imp_a / total) - (imp_b / total)) * 100.0
    except Exception:
        return None


def cloq_allowed(description):
    wr = parse_float(number("Win probability", description, percent=True))
    odd = parse_float(number("Odds", description, percent=False))
    edge = parse_float(number("Edge", description, percent=True))
    gap = parse_float(number("Market gap", description, percent=True))
    opponent_odd = parse_float(number("Opponent odds", description, percent=False))
    signal = market_signal(description)

    if wr is None or odd is None:
        return False
    if signal in CLOQ_BANNED_MARKETS:
        return False
    if wr < CLOQ_MIN_WR:
        return False
    if edge is not None and edge < CLOQ_MIN_EDGE:
        return False

    if gap is None and opponent_odd is not None:
        gap = normalized_market_gap_percent(odd, opponent_odd)

    if gap is not None:
        return abs(gap) <= CLOQ_MAX_MARKET_GAP

    # If RSS lacks Market gap and Opponent odds, trust that the Cloq RSS was
    # generated by the Cloq page builder and do not over-filter here.
    return True


def feed_selected(feed):
    if SELECTED_FEED in ("", "all", "*all"):
        return True
    return SELECTED_FEED == feed.get("key", "").lower() or SELECTED_FEED in feed.get("title", "").lower()


def build_message(feed_url, feed_title, pick_limit, feed_key=""):
    feed = feedparser.parse(feed_url)

    if feed.bozo:
        raise ValueError(f"RSS parsing error for {feed_url}: {feed.bozo_exception}")
    if not feed.entries:
        raise ValueError(f"No RSS entries found for {feed_url}")

    today = datetime.now().strftime("%d.%m.%Y")
    message = f"📅 {today}\n\n🎾 {feed_title}\n\n"
    icons = ["1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣", "6️⃣", "7️⃣", "8️⃣", "9️⃣", "🔟"]
    added = 0

    for item in feed.entries:
        if added >= pick_limit:
            break

        title = item.get("title", "")
        description = item.get("description", "") or item.get("summary", "")

        if feed_key == "cloq" and not cloq_allowed(description):
            continue

        player = extract_player(title)
        probability = extract_probability(description)
        odds = extract_odds(description)

        if not player or not probability or not odds:
            continue

        surname = player.split()[-1]
        icon = icons[added] if added < len(icons) else f"{added + 1}."
        message += f"{icon} {surname} | {probability}% | {odds}\n"
        added += 1

    if added == 0:
        raise ValueError(f"No valid items parsed from {feed_url}")

    message += "\nℹ️ Analytical preview only\n🧠 by BackstageTalks AI Engine"
    return message


def send_telegram_message(message):
    response = requests.post(
        f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage",
        json={"chat_id": CHAT_ID, "text": message, "disable_web_page_preview": True},
        timeout=30,
    )
    response.raise_for_status()


# ============================================================
# MAIN
# ============================================================

def main():
    for rss_feed in RSS_FEEDS:
        if not feed_selected(rss_feed):
            continue
        message = build_message(
            feed_url=rss_feed["url"],
            feed_title=rss_feed["title"],
            pick_limit=rss_feed["pick_limit"],
            feed_key=rss_feed.get("key", ""),
        )
        send_telegram_message(message)
        print(message)
        print("Telegram message sent successfully.")


if __name__ == "__main__":
    main()
