import os
from prediction_engine import build_all_predictions, get_top_predictions
from history_tracker import save_today_bets


# ✅ create folders safely
def ensure_path(path):
    os.makedirs(path, exist_ok=True)


# ✅ HEADER
def html_header(title):
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{title}</title>

<style>
body {{
    background-color: #1a0f0f;
    color: white;
    font-family: Arial;
    padding: 20px;
}}

h1 {{
    font-size: 36px;
    margin-bottom: 5px;
}}

.disclaimer {{
    font-size: 12px;
    color: #aaa;
    margin-bottom: 20px;
}}

.header {{
    display: flex;
    font-weight: bold;
    border-bottom: 1px solid #333;
    padding-bottom: 10px;
    margin-bottom: 10px;
}}

.row {{
    display: flex;
    background: #2a1616;
    padding: 15px;
    margin-bottom: 10px;
    border-radius: 8px;
}}

.col {{
    flex: 1;
    padding: 5px;
}}

.pick {{
    font-weight: bold;
}}

.small {{
    color: #ccc;
    font-size: 13px;
}}
</style>

</head>
<body>

<h1>Backstage Talks Tennis Picks</h1>

<div class="disclaimer">
Data generated by the Backstage Talks STAT model are for statistical and informational purposes only.
</div>
"""


# ✅ TABLE RENDER
def render_table(title, predictions):
    html = html_header(title)

    html += f"<h2>{title}</h2>"

    html += """
<div class="header">
    <div class="col">#</div>
    <div class="col">Pick</div>
    <div class="col">Opponent</div>
    <div class="col">Match time</div>
    <div class="col">Win %</div>
    <div class="col">Odds</div>
    <div class="col">Info</div>
</div>
"""

    # ✅ EMPTY CASE
    if not predictions:
        html += "<div class='row'><div class='col'>No picks available</div></div>"
        html += "</body></html>"
        return html

    # ✅ ROWS
    for i, p in enumerate(predictions, 1):
        p1 = p["player1"]
        p2 = p["player2"]
        pick = p["pick"]

        opponent = p2 if pick == p1 else p1
        prob = round(p["probability"] * 100, 1)
        odds = p["odds"] if p["odds"] else "-"
        match_time = p.get("time", "TBD")

        html += f"""
<div class="row">
    <div class="col">#{i}</div>

    <div class="col pick">
        {pick} to win
    </div>

    <div class="col">
        {opponent}
    </div>

    <div class="col small">
        {match_time}
    </div>

    <div class="col">
        {prob}%
    </div>

    <div class="col">
        {odds}
    </div>

    <div class="col small">
        Sets: 2-3<br>
        Games ~23
    </div>
</div>
"""

    html += "</body></html>"
    return html


# ✅ MAIN RUN
def run():
    print("BUILDING ALL...")
    all_preds = build_all_predictions()

    print("BUILDING TOP...")
    top_preds = get_top_predictions()

    # ✅ SAVE HISTORY (important!)
    save_today_bets(top_preds)

    # ✅ ensure folders
    ensure_path("public/839201239012")  # ALL
    ensure_path("public/777123987111")  # TOP

    # ✅ save ALL
    with open("public/839201239012/index.html", "w", encoding="utf-8") as f:
        f.write(render_table("All Matches", all_preds))

    # ✅ save TOP
    with open("public/777123987111/index.html", "w", encoding="utf-8") as f:
        f.write(render_table("Top 5 Picks", top_preds))

    print("DONE ✅")


if __name__ == "__main__":
    run()
``
